https_domains:
  - ["ogimage.frag-den-staat.de"]
  - ["weblate.frag-den-staat.de"]
  - ["metabase.frag-den-staat.de"]
  - ["forum.okfn.de", "forum.fragdenstaat.de"]
  - ["gegenrechtsschutz.de", "www.gegenrechtsschutz.de"]
  - ["nocodb.zerschlagdenstaat.de"]
