---

- name: Install Redis
  apt:
    name: redis-server
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags:
    - packages
    - redis

- name: Ensure Redis is supervised by systemd
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^supervised'
    line: supervised systemd
  tags: redis
  notify: Restart Redis service

- name: Ensure the Redis service is running
  service:
    name: redis
    state: started
    enabled: yes
  tags: redis
