---

- name: Install Redis
  ansible.builtin.apt:
    name: redis-server
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags:
    - packages
    - redis
  retries: 30
  delay: 10

- name: Ensure Redis is supervised by systemd
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^supervised'
    line: supervised systemd
  tags: redis
  notify: Restart Redis service

- name: Ensure the Redis service is running
  ansible.builtin.service:
    name: redis
    state: started
    enabled: true
  tags: redis
