---

- name: Install Redis
  apt:
    name: redis-server
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags:
    - packages
    - redis
  when: ansible_distribution_version == "20.04"

- name: Ensure Redis is supervised by systemd
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^supervised'
    line: supervised systemd
  tags: redis
  when: ansible_distribution_version == "20.04"

- name: Ensure the Redis service is running
  service: name=redis state=started enabled=yes
  tags: redis
  when: ansible_distribution_version == "20.04"
