---
- name: Install dovecot
  ansible.builtin.apt:
    name: dovecot-imapd
    state: latest
  retries: 3
  delay: 10

- name: Create group used in passwdfile
  ansible.builtin.group:
    name: "vmail"
    gid: 5000
    system: true

- name: Create vmail user
  ansible.builtin.user:
    name: "vmail"
    group: "vmail"
    uid: 5000
    home: "/var/local/vmail"
    shell: "/usr/sbin/nologin"
    system: true

- name: Create vmail directory
  ansible.builtin.file:
    state: directory
    name: /var/vmail/
    owner: vmail
    group: vmail
    mode: "0775"

- name: Create the dovecot config
  ansible.builtin.template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    mode: "0644"
  notify: restart dovecot

- name: Remove default dovecot auth file
  ansible.builtin.file:
    path: "/etc/dovecot/conf.d/10-auth.conf"
    state: absent

- name: Configure dovecot logrotate
  ansible.builtin.copy:
    src: logrotate.conf
    dest: /etc/logrotate.d/dovecot
    mode: "0644"

- name: Create dovecot passwd file
  ansible.builtin.copy:
    content: ""
    dest: "{{ dovecot_passwd_file }}"
    force: false
    owner: "root"
    group: "dovecot"
    mode: "0650"

- name: Encrypt dovecot passwords
  ansible.builtin.command:
    cmd: "doveadm pw -s {{ dovecot_passwdfile_scheme }} -p {{ item.password }}"
  with_items: "{{ email_accounts }}"
  changed_when: false
  no_log: true
  register: dovepasswd

- name: Add dovecot passwords
  ansible.builtin.lineinfile:
    dest: "{{ dovecot_passwd_file }}"
    regexp: "^{{ item.item.user }}"
    line: "{{ item.item.user }}:{{ item.stdout }}"
    state: present
  with_items: "{{ dovepasswd.results }}"
  notify: restart dovecot
  changed_when: false
  no_log: true

- name: configure imaps port in ufw
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    interface: wg0
    direction: in
  with_items:
    - imaps

- name: configure imaps port in ufw from auxiliary host ipv4
  community.general.ufw:
    rule: allow
    port: "imaps"
    proto: tcp
    from_ip: "{{ hostvars[item].host_data.global_ipv4 }}"
    direction: in
  with_items: "{{ groups['auxiliary'] }}"

- name: configure imaps port in ufw from auxiliary host ipv6
  community.general.ufw:
    rule: allow
    port: "imaps"
    proto: tcp
    from_ip: "{{ hostvars[item].host_data.global_ipv6 }}"
    direction: in
  with_items: "{{ groups['auxiliary'] }}"

- name: Ensure dovecot is started and enabled at boot.
  ansible.builtin.service:
    name: dovecot
    state: started
    enabled: true
  changed_when: false
