- name: restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
    enabled: true

- name: update postmap vmail_mailbox
  ansible.builtin.command:
    cmd: "postmap /etc/postfix/vmail_mailbox"
  notify: restart postfix
  changed_when: false

- name: update postmap vmail_domains
  ansible.builtin.command:
    cmd: "postmap /etc/postfix/vmail_domains"
  notify: restart postfix
  changed_when: false

- name: restart opendkim
  ansible.builtin.service:
    name: opendkim
    state: restarted

- name: restart opendmarc
  ansible.builtin.service:
    name: opendmarc
    state: restarted
