- name: restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
    enabled: true

- name: update postmap
  ansible.builtin.command:
    cmd: "postmap /etc/postfix/{{ item }}"
  notify: restart postfix
  changed_when: false
  with_items:
    - "vmail_domains"
    - "vmail_mailbox"

- name: restart opendkim
  ansible.builtin.service:
    name: opendkim
    state: restarted

- name: restart opendmarc
  ansible.builtin.service:
    name: opendmarc
    state: restarted
