---

- name: Create the conf folder
  ansible.builtin.file:
    path: "{{ virtualenv_path }}/conf"
    mode: "0550"
    owner: www-data
    state: directory

- name: Install python3 passlib library
  ansible.builtin.apt:
    name: python3-passlib
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags: packages

- name: Create htpassword files
  community.general.htpasswd:
    path: "{{ virtualenv_path }}/conf/htpasswd_{{ item.realm }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    owner: www-data
    group: www-data
    mode: "0550"
  with_items: "{{ htpasswd }}"
  notify: reload nginx
  tags:
    - nginx

- name: Ensure that the file permissions for static are correct
  ansible.builtin.file:
    path: "{{ django_static_root }}"
    recurse: true
    owner: "{{ gunicorn_user }}"
    group: www-data
    mode: u=rwx,g=rx,o=r
    state: directory
