---

- name: restart celery workers
  community.general.supervisorctl:
    name: "celery_{{ item.name }}"
    state: restarted
  with_items: "{{ celery_workers }}"

- name: restart celery beat
  community.general.supervisorctl:
    name: "{{ celerybeat_application_name }}"
    state: restarted
