- name: Add node key
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  retries: 30
  delay: 10

- name: Add node to the sources list
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main"
    update_cache: "{{ update_apt_cache }}"
    state: present

- name: Install node
  ansible.builtin.apt:
    name:
      - nodejs
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags: packages
  retries: 30
  delay: 10

- name: Setup pnpm
  command: corepack enable pnpm
  become: true
  become_user: root

- name: Creates public directory
  ansible.builtin.file:
    path: "{{ virtualenv_path }}/build"
    state: "directory"
    owner: "{{ gunicorn_user }}"
    mode: "0755"

- name: Install frontend dependencies
  ansible.builtin.command: pnpm install
  args:
    chdir: "{{ project_path }}"
  become: true
  become_user: "{{ gunicorn_user }}"
  tags:
    - deploy
    - deploy-frontend

- name: Build frontend bundle
  ansible.builtin.command: pnpm run build
  args:
    chdir: "{{ project_path }}"
  environment:
    ASSET_PATH: "{{ static_asset_path }}"
    SENTRY_URL: "{{ sentry_url }}"
    SENTRY_ORG: "{{ sentry_org }}"
    SENTRY_AUTH_TOKEN: "{{ sentry_auth_token }}"
    SENTRY_PROJECT: "{{ sentry_project }}"
  become: true
  become_user: "{{ gunicorn_user }}"
  changed_when: false
  tags:
    - deploy
    - deploy-frontend
