- name: Add node key
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  retries: 30
  delay: 10

- name: Add node to the sources list
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main"
    update_cache: "{{ update_apt_cache }}"
    state: present

- name: Add yarn key
  ansible.builtin.apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add yarn to the sources list
  ansible.builtin.apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    update_cache: "{{ update_apt_cache }}"
    state: present

- name: Install node
  ansible.builtin.apt:
    name:
      - nodejs
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags: packages
  retries: 30
  delay: 10

- name: Install yarn
  ansible.builtin.apt:
    name: yarn
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags: packages
  retries: 30
  delay: 10

- name: Creates public directory
  ansible.builtin.file:
    path: "{{ virtualenv_path }}/build"
    state: "directory"
    owner: "{{ gunicorn_user }}"
    mode: "0755"

- name: Setup yarn build script
  ansible.builtin.template:
    src: yarn-build.sh.j2
    dest: "{{ virtualenv_path }}/yarn-build.sh"
    mode: "0755"

- name: Run yarn setup script
  ansible.builtin.command: "{{ virtualenv_path }}/yarn-build.sh"
  become: true
  become_user: "{{ gunicorn_user }}"
  changed_when: false
  tags:
    - deploy
    - deploy-frontend
