- name: Setup Node.js
  ansible.builtin.import_role:
    name: nodejs

- name: Creates public directory
  ansible.builtin.file:
    path: "{{ virtualenv_path }}/build"
    state: "directory"
    owner: "{{ gunicorn_user }}"
    mode: "0755"

- name: Install frontend dependencies
  ansible.builtin.command: pnpm install
  args:
    chdir: "{{ project_path }}"
  become: true
  become_user: "{{ gunicorn_user }}"
  tags:
    - deploy
    - deploy-frontend
  changed_when: false

- name: Build frontend bundle
  ansible.builtin.command: pnpm run build
  args:
    chdir: "{{ project_path }}"
  environment:
    ASSET_PATH: "{{ static_asset_path }}"
    SENTRY_URL: "{{ sentry_url }}"
    SENTRY_ORG: "{{ sentry_org }}"
    SENTRY_AUTH_TOKEN: "{{ sentry_auth_token }}"
    SENTRY_PROJECT: "{{ sentry_project }}"
  become: true
  become_user: "{{ gunicorn_user }}"
  changed_when: false
  tags:
    - deploy
    - deploy-frontend
