---

- name: Install Supervisor
  ansible.builtin.apt:
    name: supervisor
    update_cache: "{{ update_apt_cache }}"
    state: present

- name: Ensure supervisor service is started
  ansible.builtin.service:
    name: supervisor
    state: started
    enabled: true

- name: Create the Supervisor config file
  ansible.builtin.template:
    src: "supervisor_{{ item }}.j2"
    dest: "/etc/supervisor/conf.d/{{ item }}.conf"
    backup: true
    mode: "600"
  with_items:
    - "app_gunicorn"
    - "app_uvicorn"

- name: Re-read the Supervisor config files
  community.general.supervisorctl:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ application_name }}_gunicorn"
    - "{{ application_name }}_uvicorn"
