---

- name: Ensure gunicorn is installed
  pip:
    virtualenv: "{{ virtualenv_path }}"
    # extra_args: --user
    name: "gunicorn"
  become: true
  become_user: "{{ gunicorn_user }}"

- name: Create the application log folder
  file: path={{ application_log_dir }}
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0774
        state=directory

- name: Create the application log file
  file: path={{ application_log_file }}
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0664
        state=touch

- name: Create the gunicorn/uvicorn script file
  template:
    src: "{{ item }}_start.j2"
    dest: "{{ virtualenv_path }}/bin/{{ item }}_start"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    mode: "0755"
    backup: true
  with_items:
    - gunicorn
    - uvicorn
  notify: restart app server
  tags:
    - deploy
    - deploy-backend
    - deploy-web