# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

#- repo: https://github.com/ansible/ansible-lint
#  rev: v6.20.3 # put latest release tag from https://github.com/ansible/ansible-lint/releases/
#  hooks:
#    - id: ansible-lint

- repo: local
  hooks:
    - id: ansible-vault
      name: ansible-vault
      entry: ./git_hooks/check_vault.sh
      language: script
