---

- name: "Basic setup, networking, monitoring"
  hosts: all
  vars_files:
    - env_vars/base.yml
    - env_vars/secrets.yml
    - env_vars/production.yml
  roles:
    - base
    - network
    - check_mk

- name: Create a db server
  hosts: db


- name: Create a mail server
  hosts: mail

- name: Create a web {{ application_name }}
  hosts: web:app:db:mail
  become: true
  become_user: root
  pre_tasks:
    - name: Send Slack notification message on start deployment
      become: false
      slack:
        token: '{{ slack_token }}'
        msg: 'Deployment start on {{ inventory_hostname }}'
        username: fds-bot
        channel: '#fragdenstaat-alerts'
      when: slack_token is defined
      tags:
        - deploy
        - deploy-backend
        - deploy-web
        - deploy-frontend
  post_tasks:
    - name: Send Slack notification message on finished deployment
      become: false
      slack:
        token: '{{ slack_token }}'
        msg: 'Deployment finished on {{ inventory_hostname }}'
        username: fds-bot
        channel: '#fragdenstaat-alerts'
      when: slack_token is defined
      tags:
        - deploy
        - deploy-backend
        - deploy-web
        - deploy-frontend
  vars:
    - update_apt_cache: true
  vars_files:
    - env_vars/base.yml
    - env_vars/secrets.yml
    - env_vars/production.yml

  roles:
    - base
    - db
    - memcached
    - rabbitmq
    - elasticsearch
    - redis
    - web
    - celery
    - certbot
    - nginx
    - postfix
    - dovecot
    - backup
    - check_mk
