[project]
name = "fragdenstaat-de-ansible"
version = "0.1.0"
description = "Ansible repo for managing FragDenStaat.de"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.0,<12.0",
    "ansible-lint>=25.5.0",
    "yamllint>=1.37.1",
]
