---
# for ansible-lint
collections:
  - ansible.posix
  - community.general
  - community.docker
  - community.mysql
  - { name: community.postgresql, version: 4.2.0 }
  - community.rabbitmq
  - community.crypto
  - community.libvirt
  - { name: containers.podman, version: ">=1.20.2"}
