---

- name: Add VPN client
  hosts: vpn
  vars_prompt:

    - name: client_name
      prompt: "Name of the client?"
      private: no

    - name: peer_id
      prompt: "Peer id < 200?"
      private: no

  tasks:
    - name: Generate new private key locally
      local_action:
        module: shell
        cmd: "wg genkey"
      run_once: True
      register: private_key

    - name: Generate new public key locally
      local_action:
        module: command
        args:
          argv: ["wg", "pubkey"]
        stdin: "{{ private_key.stdout }}"
      register: public_key

    - name: Include role vars
      include_vars: "roles/wireguard/defaults/main.yml"

    - name: Make peer config
      local_action:
        module: template
        src: "roles/wireguard/templates/client.conf.j2"
        dest: "FDS VPN {{ peer_id }}.conf"

    - name: Include role vars
      include_vars: "env_vars/vpnclients.yml"

    - name: Store peer config
      local_action:
        module: template
        src: "roles/wireguard/templates/clientgroups.yml.j2"
        dest: "env_vars/vpnclients.yml"

    - name: Print public key
      local_action:
        module: debug
        var: public_key.stdout
