---
# Application settings.
requirements_file: "{{ project_path }}/requirements-production.txt"

# Django environment variables.
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_CONFIGURATION: "{{ django_configuration }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  DJANGO_MEDIA_ROOT: "{{ django_media_root }}"
  DJANGO_STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_URL: "postgres://{{ db_user }}:{{ db_password }}@{{ db_host }}/{{ db_name }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_HOST: "{{ db_host }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  DJANGO_MEMCACHED_LOCATION: "{{ hostvars[groups['cache'][0]].host_data.site_ipv4 }}"
  DJANGO_ELASTICSEARCH_HOSTS: "{% for host in groups['search'] %}http://{{ hostvars[host].host_data.site_ipv4 }}:9200{%if not loop.last %},{% endif %}{% endfor %}"
  DJANGO_CELERY_BROKER_URL: "{{ celery_broker_url }}"
  DJANGO_CELERY_WORKER_SEND_TASK_EVENTS: "True"
  DJANGO_CELERY_TASK_SEND_SENT_EVENT: "True"
  DJANGO_EMAIL_HOST: "{{ email_host }}"
  DJANGO_EMAIL_HOST_USER: "{{ email_host_user }}"
  DJANGO_EMAIL_HOST_PASSWORD: "{{ email_host_password }}"
  DJANGO_FOI_EMAIL_HOST: "{{ foi_email_host }}"
  DJANGO_FOI_EMAIL_HOST_USER: "{{ foi_email_host_user }}"
  DJANGO_FOI_EMAIL_HOST_PASSWORD: "{{ foi_email_host_password }}"
  DJANGO_FOI_EMAIL_ACCOUNT_PASSWORD: "{{ foi_email_host_password }}"
  DJANGO_FOI_EMAIL_HOST_IMAP: "{{ foi_email_host }}"
  DJANGO_FOI_EMAIL_ACCOUNT_NAME: "{{ foi_email_host_user }}"
  DJANGO_BOUNCE_EMAIL_HOST_IMAP: "{{ bounce_email_host }}"
  DJANGO_BOUNCE_EMAIL_ACCOUNT_NAME: "{{ bounce_email_host_user }}"
  DJANGO_BOUNCE_EMAIL_ACCOUNT_PASSWORD: "{{ bounce_email_host_password }}"
  DJANGO_UNSUBSCRIBE_EMAIL_HOST_IMAP: "{{ unsubscribe_email_host }}"
  DJANGO_UNSUBSCRIBE_EMAIL_ACCOUNT_NAME: "{{ unsubscribe_email_host_user }}"
  DJANGO_UNSUBSCRIBE_EMAIL_ACCOUNT_PASSWORD: "{{ unsubscribe_email_host_password }}"
  DJANGO_GEOIP_PATH: "{{ django_geoip_path }}"
  DJANGO_LOG_DIR: "{{ application_log_dir }}"
  DJANGO_SECRET_URL_ADMIN: "{{ django_secret_url_admin }}"
  DJANGO_SENTRY_DSN: "{{ django_sentry_dsn }}"
  DJANGO_SENTRY_PUBLIC_DSN: "{{ django_sentry_public_dsn }}"
  STRIPE_PUBLIC_KEY: "{{ stripe_public_key }}"
  STRIPE_PRIVATE_KEY: "{{ stripe_private_key }}"
  STRIPE_WEBHOOK_CC_SIGNING_KEY: "{{ stripe_webhook_cc_signing_key }}"
  STRIPE_WEBHOOK_SEPA_SIGNING_KEY: "{{ stripe_webhook_sepa_signing_key }}"
  STRIPE_WEBHOOK_SOFORT_SIGNING_KEY: "{{ stripe_webhook_sofort_signing_key }}"
  PAYPAL_CLIENT_ID: "{{ paypal_client_id }}"
  PAYPAL_CLIENT_SECRET: "{{ paypal_client_secret }}"
  PAYPAL_API_URL: "{{ paypal_api_url }}"
  PAYPAL_WEBHOOK_ID: "{{ paypal_webhook_id }}"
  SUSPICIOUS_ASN: "{{ suspicious_asn_list }}"
  SLACK_WEBHOOK_URL: "{{ slack_webhook_url }}"
  MATOMO_API_URL: "{{ matomo_api_url }}"
  YELP_API_KEY: "{{ yelp_api_key }}"
  MAPBOX_API_KEY: "{{ mapbox_api_key }}"
  FOURSQUARE_API_KEY: "{{ foursquare_api_key }}"
  GOOGLE_PLACES_API_KEY: "{{ google_places_api_key }}"
  HERE_GEOCODE_API_KEY: "{{ here_geocode_api_key }}"
  TELNYX_APP_ID: "{{ telnyx_app_id }}"
  TELNYX_API_KEY: "{{ telnyx_api_key }}"
  TELNYX_PUBLIC_KEY: "{{ telnyx_public_key }}"
  TELNYX_FROM_NUMBER: "{{ telnyx_from_number }}"
  DJANGO_TESSERACT_DATA_PATH: "{{ tesseract_data_path }}"
  FDS_LEGAL_BACKUP_CREDENTIALS: "{{ fds_legal_backup_credentials }}"
  FDS_LEGAL_BACKUP_URL: "{{ fds_legal_backup_url }}"
  FRONTEX_CAPTCHA_MODEL_PATH: "{{ frontex_captcha_model_path }}"
  DONATION_BACKUP_URL: "{{ donation_backup_url }}"
  DONATION_BACKUP_CREDENTIALS: "{{ donation_backup_credentials }}"
  FOI_MAIL_SERVER_HOST: "{{ foi_mail_server_host }}"
  FOI_MAIL_DOMAIN: "{{ foi_mail_domain }}"
  SITE_URL: "{{ site_url }}"
  MEDIA_URL: "{{ media_url }}"
  STATIC_URL: "{{ static_url }}"
  ALLOWED_HOSTS: "{{ allowed_hosts }}"
  DEFAULT_FROM_EMAIL: "{{ fds_default_from_email }}"
  SERVER_EMAIL: "{{ fds_server_email }}"
  SITE_EMAIL: "{{ fds_site_email }}"
  PAPERLESS_API_URL: "{{ paperless_api_url }}"
  PAPERLESS_API_TOKEN: "{{ paperless_api_token }}"
  PAPERLESS_UPLOADED_TYPE: "{{ paperless_uploaded_type }}"
  PAPERLESS_REQUEST_FIELD: "{{ paperless_request_field }}"
  FROIDE_EVIDENCECOLLECTION_NOCODB_API_TOKEN: "{{ froide_evidencecollection_nocodb_api_token }}"
  FROIDE_EVIDENCECOLLECTION_NOCODB_API_URL: "{{ froide_evidencecollection_nocodb_api_url }}"
  FROIDE_EVIDENCECOLLECTION_NOCODB_EVIDENCE_TABLE: "{{ froide_evidencecollection_nocodb_evidence_table }}"
  FROIDE_EVIDENCECOLLECTION_NOCODB_GROUP_TABLE: "{{ froide_evidencecollection_nocodb_group_table }}"
  FROIDE_EVIDENCECOLLECTION_NOCODB_PERSON_TABLE: "{{ froide_evidencecollection_nocodb_person_table }}"
  FROIDE_EVIDENCECOLLECTION_NOCODB_SOURCE_TABLE: "{{ froide_evidencecollection_nocodb_source_table }}"
  PAYMENT_HOST: "{{ payment_host }}"
  NEWSLETTER_PIXEL_LOG: "{{ nginx_pixel_log_file }}"
