- name: Update docker-compose.yml
  ansible.builtin.lineinfile:
    path: "{{ hostvars[inventory_hostname].dockerupdate_compose_lines[item].path }}/docker-compose.yml"
    regexp: "{{ hostvars[inventory_hostname].dockerupdate_compose_lines[item].regexp }}"
    line: "{{ hostvars[inventory_hostname].dockerupdate_compose_lines[item].line }}"
    state: present
  register: composestatus
  with_items: "{{ dockerupdate_compose_lines }}"
  when: dockerupdate_compose_lines is defined

- name: Pull docker images
  community.docker.docker_compose_v2_pull:
    project_src: "{{ hostvars[inventory_hostname].dockerupdate_compose_lines[item].path }}"
  register: pullstatus
  with_items: "{{ dockerupdate }}"
  when: dockerupdate is defined

- name: Restart docker container
  community.docker.docker_compose_v2:
    project_src: "{{ hostvars[inventory_hostname].dockerupdate_compose_lines[item].path }}"
    recreate: always
    state: restarted
    wait: true
  with_items: "{{ dockerupdate }}"
  when:
    - pullstatus is defined and
      pullstatus.changed or
      composestatus is defined and
      composestatus.changed
  tags: skip_ansible_lint
