- name: Install borgbackup
  ansible.builtin.apt:
    pkg: borgbackup

- name: Create backupscript
  ansible.builtin.template:
    dest: /root/backup.sh
    src: borg.sh.j2
    mode: "0750"

- name: Generate ssh key for borg repo
  ansible.builtin.user:
    name: "root"
    generate_ssh_key: true
    ssh_key_file: .ssh/id_borg
    ssh_key_type: ed25519

- name: Create ssh config
  ansible.builtin.template:
    src: borg-ssh-config.j2
    dest: /root/.ssh/config
    mode: "0640"

- name: Create backup cronjob
  ansible.builtin.cron:
    name: Backup
    user: root
    job: /root/backup.sh 2>&1 > /var/log/backup.log
    minute: "0"
    hour: "1"
    dom: "*"
    month: "*"
    dow: "*"
