- name: Create celery exporter directory
  ansible.builtin.file:
    path: /opt/celery_exporter
    state: directory
    mode: "0755"
  tags: exporter

- name: Install celery exporter
  ansible.builtin.get_url:
    url: https://github.com/danihodovic/celery-exporter/releases/download/v0.10.4/celery-exporter
    dest: /opt/celery_exporter/celery_exporter
    mode: "0755"
  notify: Restart celery exporter
  tags: exporter

- name: Install supervisord
  ansible.builtin.apt:
    name: supervisor

- name: Configure supervisord
  ansible.builtin.template:
    src: exporter/celery_supervisor.conf.j2
    dest: /etc/supervisor/conf.d/celery_exporter.conf
    mode: "0640"
  notify: Restart celery exporter
  tags: exporter

- name: Activate supervisord config
  community.general.supervisorctl:
    name: celery_exporter
    state: present
  notify: Restart celery exporter
  tags: exporter

- name: Configure firewall (celery_exporter)
  community.general.ufw:
    port: "9808"
    proto: tcp
    from_ip: 192.168.100.5
    rule: allow
  tags: exporter
