---

- name: Include monitor-server.yml
  ansible.builtin.include_tasks: monitor-server.yml
  when: graylog is true or grafana is true or prometheus is true
  tags:
    - grafana
    - graylog
    - prometheus

# - name: Include grafana_extra.yml
#  ansible.builtin.include_tasks: grafana_extra.yml
#  when: grafana is true
#  tags: grafana

- name: Include rsyslog.yml
  ansible.builtin.include_tasks: rsyslog.yml
  when: rsyslog is true
  tags: rsyslog

- name: Include prometheus exporter
  ansible.builtin.include_tasks: "exporters/{{ item }}.yml"
  with_items: "{{ monitor_prometheus_exporters }}"
  when:
    - monitor_prometheus_exporters is defined
    - monitor_prometheus_exporters | length > 0
  tags: exporter

- name: Include sidecar.yml
  ansible.builtin.include_tasks: sidecar.yml
  when: sidecar is defined
  tags: sidecar
