- name: Install rsyslog
  ansible.builtin.apt:
    pkg: rsyslog
  notify: Restart rsyslog
  tags: rsyslog

- name: Create graylog config for rsyslog
  ansible.builtin.template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/10-graylog.conf
    mode: "0644"
  notify: Restart rsyslog
  tags: rsyslog
