- name: Create statsd exporter directory
  ansible.builtin.file:
    path: /opt/statsd_exporter
    state: directory
    mode: "0755"
  tags: exporter

- name: Install statsd exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/statsd_exporter/releases/download/v0.25.0/statsd_exporter-0.25.0.linux-amd64.tar.gz
    dest: /opt/statsd_exporter
    extra_opts:
      - "--strip-components=1"
    remote_src: true
  notify: Restart statsd exporter
  tags: exporter

- name: Install supervisord
  ansible.builtin.apt:
    name: supervisor

- name: Configure supervisord
  ansible.builtin.template:
    src: exporter/statsd_supervisor.conf.j2
    dest: /etc/supervisor/conf.d/statsd_exporter.conf
    mode: "0644"
  notify: Restart statsd exporter
  tags: exporter

- name: Activate supervisord config
  community.general.supervisorctl:
    name: statsd_exporter
    state: present
  notify: Restart statsd exporter
  tags: exporter

- name: Configure firewall (statsd_exporter)
  community.general.ufw:
    port: "9102"
    proto: tcp
    from_ip: 192.168.100.5
    rule: allow
  tags: exporter
