- name: Install script dependencies
  ansible.builtin.apt:
    name:
      - file
      - jq
      - smartmontools
    state: present
  retries: 30
  delay: 10

- name: Copy scripts
  ansible.builtin.copy:
    src: plugins/
    dest: /usr/lib/nagios/plugins/
    owner: root
    group: nagios
    mode: "0750"

- name: Add options for raid check to sudoers
  community.general.sudoers:
    name: allow-dmsetup
    state: present
    user: nagios
    commands: "/sbin/dmsetup status --noflush"
  tags: sudo

- name: Add options for docker check to sudoers
  community.general.sudoers:
    name: allow-dockercheck
    state: present
    user: nagios
    commands: "/usr/lib/nagios/plugins/check_docker --status running"
  when: "'docker = 1' in icinga.vars"
  tags: sudo

- name: Add options for smart check to sudoers
  community.general.sudoers:
    name: allow-smartcheck
    state: present
    user: nagios
    commands: "/usr/lib/nagios/plugins/check_smart"
  tags: sudo

- name: Add options for mysql check to sudoers
  community.general.sudoers:
    name: allow-mysqlcheck
    state: present
    user: nagios
    commands: "/usr/lib/nagios/plugins/check_mysql"
  when: "'mysql = 1' in icinga.vars"
  tags: sudo

- name: Grant check_postgres access as fragdenstaat user
  community.general.sudoers:
    name: nagiosaspostgres
    state: present
    user: nagios
    runas: fragdenstaat_de
    commands: /usr/lib/nagios/plugins/check_postgres
  when: "'postgres = 1' in icinga.vars"
  tags: sudo

- name: Add options for supervisor check to sudoers
  community.general.sudoers:
    name: allow-supervisorcheck
    state: present
    user: nagios
    commands: /usr/bin/supervisorctl status
  when: "'supervisor = 1' in icinga.vars"
  tags: sudo
