---

- name: Setup fdsbot Git repo
  git:
    repo: "{{ fdsbot_git_repo }}"
    dest: "{{ fdsbot_dir }}"
    update: true
    force: true
  become_user: fdsbot
  notify: restart fdsbot

- name: Set fdsbot systemd service
  template:
    src: fdsbot.service.j2
    dest: /etc/systemd/system/fdsbot.service
    mode: 0444
  notify: restart fdsbot

- name: Start fdsbot service
  systemd:
    name: fdsbot
    state: started
    daemon_reload: yes
