---
- name: Ensure postfix and dependencies are installed
  ansible.builtin.apt:
    pkg:
      - postfix
      - postfix-pgsql
      - postfix-pcre
      - postfix-policyd-spf-python
    state: present
  retries: 3
  delay: 10

- name: Ensure postfix is started and enabled at boot.
  ansible.builtin.service:
    name: postfix
    state: started
    enabled: true

- name: configure mailname
  ansible.builtin.copy:
    content: "{{ domain_name }}"
    dest: /etc/mailname
    mode: "0644"

- name: Install postfix main.cf config
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    mode: "0644"
  notify: restart postfix

- name: Install postfix master.cf config
  ansible.builtin.template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    mode: "0644"
  notify: restart postfix

- name: Install transport
  ansible.builtin.copy:
    src: transport
    dest: /etc/postfix/transport
    mode: "0600"
  notify: update transport postmap

- name: Install postfix sasl_passwd
  ansible.builtin.template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    mode: "0600"
  notify: update sasl_passwd postmap

- name: Install vmail_domains
  ansible.builtin.template:
    src: vmail_domains.j2
    dest: /etc/postfix/vmail_domains
    mode: "0600"
  notify: update postmap vmail_domains

- name: Install vmail_mailbox
  ansible.builtin.template:
    src: vmail_mailbox.j2
    dest: /etc/postfix/vmail_mailbox
    mode: "0600"
  notify: update postmap vmail_mailbox

- name: Install virtual alias map configuration
  ansible.builtin.template:
    src: postgres-virtual-alias-maps.cf.j2
    dest: /etc/postfix/postgres-virtual-alias-maps.cf
    mode: "0600"
  notify:
    - update postmap vmail_domains
    - update postmap vmail_mailbox

- name: Add reject domains file
  ansible.builtin.copy:
    src: reject_domains
    dest: /etc/postfix/reject_domains
    mode: "0600"

- name: Add blocklisted recipients file
  ansible.builtin.copy:
    src: blocklisted_recipients
    dest: /etc/postfix/blocklisted_recipients
    mode: "0600"

- name: Add helo reject file
  ansible.builtin.template:
    src: reject_helo.j2
    dest: /etc/postfix/reject_helo
    mode: "0644"

- name: Install custom rsyslog logrotate
  ansible.builtin.template:
    src: rsyslog.j2
    dest: /etc/logrotate.d/rsyslog
    mode: "0644"

- name: Install custom mail logrotate
  ansible.builtin.template:
    src: logrotate_mail.j2
    dest: /etc/logrotate.d/mail
    mode: "0600"

- name: Get file info for /var/log/mail.log.1
  ansible.builtin.stat:
    path: /var/log/mail.log.1
  register: mail_log_rotated

- name: Make sure log permission is present
  ansible.posix.acl:
    path: /var/log/mail.log
    entity: "{{ gunicorn_user }}"
    etype: user
    permissions: r
    state: present
  when: not mail_log_rotated.stat.exists

- name: configure smtp ports in firewall
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - smtp
    - ssmtp
    - submission

- name: Import opendkim.yml
  ansible.builtin.import_tasks: opendkim.yml

- name: Import opendmarc.yml
  ansible.builtin.import_tasks: opendmarc.yml

- name: Import spf.yml
  ansible.builtin.import_tasks: spf.yml
