---

- name: Ensure postfix and dependencies are installed
  apt: name={{ item }} state=present
  with_items:
    - postfix
    - postfix-pgsql
    - postfix-pcre

- name: Ensure postfix is started and enabled at boot.
  service: name=postfix state=started enabled=yes

- name: configure mailname
  copy: content={{ domain_name }} dest=/etc/mailname

- name: Install postfix main.cf config
  template: src=main.cf.j2 dest=/etc/postfix/main.cf
  notify: restart postfix

- name: Install postfix master.cf config
  template: src=master.cf.j2 dest=/etc/postfix/master.cf
  notify: restart postfix

- name: Install vmail_domains
  template: src=vmail_domains.j2 dest=/etc/postfix/vmail_domains
  notify: update postmap

- name: Install vmail_mailbox
  template: src=vmail_mailbox.j2 dest=/etc/postfix/vmail_mailbox
  notify: update postmap

- name: Install virtual alias map configuration
  template: src=postgres-virtual-alias-maps.cf.j2 dest=/etc/postfix/postgres-virtual-alias-maps.cf
  notify: update postmap

- name: Add reject domains file
  copy: src=reject_domains dest=/etc/postfix/reject_domains
  notify: update postmap

- name: Install custom rsyslog logrotate
  template: src=rsyslog.j2 dest=/etc/logrotate.d/rsyslog

- name: Install custom mail logrotate
  template: src=logrotate_mail.j2 dest=/etc/logrotate.d/mail

- stat: path=/var/log/mail.log.1
  register: mail_log_rotated

- name: Make sure log permission is present
  command: /usr/bin/setfacl -m u:{{ gunicorn_user }}:r /var/log/mail.log
  when: mail_log_rotated.stat.exists == False

- name: configure smtp ports in firewall
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
  - smtp
  - ssmtp
  - submission

- import_tasks: opendkim.yml
