---
- name: opendkim packages are installed
  ansible.builtin.apt:
    pkg:
      - opendkim
      - opendkim-tools
    state: present

- name: opendkim socket configured
  ansible.builtin.lineinfile:
    dest: /etc/default/opendkim
    regexp: "^SOCKET="
    line: 'SOCKET="inet:12301@localhost"'
  notify:
    - restart opendkim

- name: opendkim directory present
  ansible.builtin.file:
    path: /etc/opendkim/keys
    state: directory
    owner: opendkim
    group: opendkim
    mode: "0750"

- name: opendkim TrustedHosts present
  ansible.builtin.copy:
    src: TrustedHosts
    dest: /etc/opendkim/TrustedHosts
    mode: "0600"
  notify:
    - restart opendkim

- name: opendkim is configured
  ansible.builtin.template:
    src: opendkim/opendkim.conf.j2
    dest: /etc/opendkim.conf
    mode: "0644"
  notify:
    - restart opendkim

- name: opendkim KeyTable is configured
  ansible.builtin.template:
    src: opendkim/KeyTable.j2
    dest: /etc/opendkim/KeyTable
    mode: "0600"
  notify:
    - restart opendkim

- name: opendkim SigningTable is configured
  ansible.builtin.template:
    src: opendkim/SigningTable.j2
    dest: /etc/opendkim/SigningTable
    mode: "0600"
  notify:
    - restart opendkim

- name: ensure signing key is present
  ansible.builtin.stat:
    path: /etc/opendkim/keys/{{ dkim_selector }}.private
    get_md5: false
  register: dkim_key

- name: generate signing key
  ansible.builtin.command:
    cmd: "opendkim-genkey -s {{ dkim_selector }} -d {{ dkim_domains[0] }} -D /etc/opendkim/keys"
  when: not dkim_key.stat.exists
  notify:
    - restart opendkim

- name: ensure signing key owner
  ansible.builtin.file: path=/etc/opendkim/keys/{{ dkim_selector }}.private owner=opendkim group=opendkim mode=700

- name: opendkim is started
  ansible.builtin.service: name=opendkim state=started enabled=yes
