---
- name: restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: reload ufw
  ansible.builtin.service:
    name: ufw
    state: restarted

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: apt update
  ansible.builtin.apt:
    update_cache: true
  retries: 3
  delay: 10

- name: update initramfs
  ansible.builtin.command: update-initramfs -u
  changed_when: true

- name: dpkg-reconfigure dropbear-initramfs
  ansible.builtin.command: dpkg-reconfigure dropbear-initramfs
  changed_when: true
