---
- name: restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: reload ufw
  ansible.builtin.service:
    name: ufw
    state: restarted

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
