---

virtualenv_python_version: python3.8

git_branch: master

poppler_version: 0.89.0

celery_broker_url: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@localhost/{{ rabbitmq_application_vhost }}"
