---
- name: restart app server
  community.general.supervisorctl:
    name: "{{ application_name }}_{{ item }}"
    state: restarted
  with_items:
    - "gunicorn"
    - "uvicorn"
  notify:
    - restart memcached

- name: restart onion app server
  community.general.supervisorctl:
    name: "{{ application_name }}_{{ item }}_onion"
    state: restarted
  when: onion_service_enabled
  with_items:
    - "gunicorn"
    - "uvicorn"
  notify:
    - restart memcached

- name: restart CMS app server
  community.general.supervisorctl:
    name: "{{ item }}_onion"
    state: restarted
  when: onion_service_enabled
  with_items: "{{ cms_sites }}"
  notify:
    - restart memcached

- name: restart memcached
  ansible.builtin.service:
    name: memcached
    state: restarted
    enabled: true

- name: restart tor
  ansible.builtin.service:
    name: tor
    state: restarted

- name: restart apparmor
  ansible.builtin.service:
    name: apparmor
    state: restarted
