---

- name: restart app server
  supervisorctl:
    name: "{{ application_name }}_{{ item }}"
    state: restarted
  with_items:
    - "gunicorn"
    - "uvicorn"
  notify:
    - restart memcached

- name: restart onion app server
  supervisorctl:
    name: "{{ application_name }}_{{ item }}_onion"
    state: restarted
  when: onion_service_enabled
  with_items:
    - "gunicorn"
    - "uvicorn"
  notify:
    - restart memcached

- name: restart memcached
  service:
    name: memcached
    state: restarted
    enabled: true

- name: restart tor
  service:
    name: tor
    state: restarted

- name: restart apparmor
  service:
    name: apparmor
    state: restarted
