---

- name: Setup Weblate Git repo
  ansible.builtin.git:
    repo: "{{ weblate_git_repo }}"
    dest: "{{ weblate_dir }}"
    version: a214e5d3d84c85e61a1453c08d998be67cef1a75
  become: true
  notify: restart weblate

- name: Set weblate docker compose override
  ansible.builtin.template:
    src: docker-compose.override.yml.j2
    dest: "{{ weblate_dir }}/docker-compose.override.yml"
    mode: "0644"
  notify: restart weblate

- name: Set weblate systemd service
  ansible.builtin.template:
    src: weblate.service.j2
    dest: /etc/systemd/system/weblate.service
    mode: "0444"

- name: Start weblate service
  ansible.builtin.systemd:
    name: weblate
    state: started
    daemon_reload: true

- name: Create the Nginx site configuration
  ansible.builtin.template:
    src: nginx-site.j2
    dest: "/etc/nginx/sites-available/{{ weblate_domain }}"
    mode: "0644"
    backup: true
  notify: reload nginx

- name: Ensure that the application site is enabled
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ weblate_domain }}"
    dest: "/etc/nginx/sites-enabled/{{ weblate_domain }}"
    state: link
  notify: reload nginx

- name: Import setup_backup.yml
  ansible.builtin.import_tasks: setup_backup.yml
