---
git_repo: https://github.com/okfde/fragdenstaat_de.git

ssh_port: "22"
## in secrets.yml
# ssh_users:
#   - name: <name>
#     ssh_public_keys:
#       - ""
#     revoked_ssh_public_keys:
#       - ""

network_vlan:
  id: 4000

# Declare the VPN subnet
vpn_network: "10.9.0."
vpn_network_subnet: "10.9.0.0/24"
vpn_networkv6: "fc00::"
vpn_networkv6_subnet: "fc00::0/120"

maintenance: false
maintenance_media: false
maintenance_admin_ip: false
update_apt_cache: true

hostname: "{{ inventory_hostname }}"
project_name: fragdenstaat.de
application_name: fragdenstaat_de
mail_domain: mail.fragdenstaat.de
domain_name: fragdenstaat.de
web_server_name: fragdenstaat.de
web_server_url: "https://{{ web_server_name }}"
wsweb_server_url: "wss://{{ web_server_name }}"
media_server_name: media.frag-den-staat.de
media_server_url: "https://{{ media_server_name }}"
static_server_name: static.frag-den-staat.de
static_server_url: "https://{{ static_server_name }}"
static_asset_path: "{{ static_server_url }}/static/"

foi_mail_server_host: "mail.fragdenstaat.de"
foi_mail_domain: '"fragdenstaat.de","echtemail.de"'
site_url: "https://fragdenstaat.de"
media_url: "https://media.frag-den-staat.de/files/"
static_url: "https://static.frag-den-staat.de/static/"
allowed_hosts: '"fragdenstaat.de","media.frag-den-staat.de","testserver"'
payment_host: "fragdenstaat.de"

external_media_storage: true
external_media_storage_src: "/home/storage-box/home"
external_media_storage_target: "/mnt/schoch"
external_media_storage_unitname: "mnt-schoch"

letsencrypt_enabled: true
letsencrypt_registration_email: root@fragdenstaat.de
letsencrypt_tmp_dir: /opt/letsencrypt/tmp
letsencrypt_renew_hooks:
  "mail.fragdenstaat.de": "systemctl reload nginx postfix dovecot"

db_host: "127.0.0.1"
db_name: "{{ application_name }}"
db_user: "{{ application_name }}"
## in secets.yml
# db_password:
db_user_readonly: "{{ application_name }}_readonly"
## in secets.yml
# db_password_readonly:
db_reporting_schema: "reporting"
db_user_reporting: "fds_report"
# db_password_reporting

collect_release_info: true

# Gunicorn settings.
gunicorn_num_workers: 10
gunicorn_user: "{{ application_name }}"
gunicorn_user_uid: 1001
gunicorn_group: webapps
gunicorn_group_gid: 998
uvicorn_num_workers: 2
gunicorn_cmssite_num_workers: 2

onion_service_enabled: true
gunicorn_onion_num_workers: 2
uvicorn_onion_num_workers: 1
onion_web_server: "fdstaat23zv6kdmntgkvdzkr7hipl5oqswwi3xawzkj2w2gwsbxmrwyd.onion"
onion_web_server_url: "http://{{ onion_web_server }}"
onion_wsweb_server_url: "ws://{{ onion_web_server }}"
onion_media_server: "media.fdscdncc46svip3qd3vtyrrw7435sdftp4wd3crarr3m6iwenitoryad.onion"
onion_static_server: "static.fdscdncc46svip3qd3vtyrrw7435sdftp4wd3crarr3m6iwenitoryad.onion"
onion_media_server_url: "http://{{ onion_media_server }}"
onion_static_server_url: "http://{{ onion_static_server }}"
onion_static_url: "http://{{ onion_static_server }}/static/"
onion_media_url: "http://{{ onion_media_server }}/files/"
onion_nginx_static_dir: "/var/www/fragdenstaat.de/public/onion/static/"
onion_services:
  onion_web:
    hostname: "fdstaat23zv6kdmntgkvdzkr7hipl5oqswwi3xawzkj2w2gwsbxmrwyd.onion"
    port: 80
    internal_port: 8050
  onion_static_media:
    hostname: "fdscdncc46svip3qd3vtyrrw7435sdftp4wd3crarr3m6iwenitoryad.onion"
    port: 80
    internal_port: 8051

# Temporary here
virtualenv_path: "/var/www/fragdenstaat.de"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "/var/www/fragdenstaat.de/logs"

## in secrets.yml
# htpasswd:
#   - name: user
#     password: password
#     realm: admin

django_media_root: "/var/www/fragdenstaat.de/storage/files"
django_static_root: "/var/www/fragdenstaat.de/public/static"

django_settings_file: "{{ application_name }}.settings.production"
django_configuration: "FragDenStaat"

django_geoip_path: "/var/www/fragdenstaat.de/data"
frontex_captcha_model_path: "/var/www/fragdenstaat.de/data/model.pth"

## in secrets.yml
# django_secret_url_admin: "admin"

## in secrets.yml
# protected_urls:
#   - url: "/admin/"
#     realm: admin
#     only_ip: []

## in secrets.yml
# rate_limited_urls:
#   - url: /account/login/
#     zone: login
#     auth: false

release_repo: okfde/fragdenstaat_de

celery_workers:
  - name: celery
    queues: "celery"
    worker: 3
  - name: mail
    queues: "emailfetch,email"
    worker: 1
  - name: mailsend
    queues: "emailsend"
    worker: 2
  - name: mailsend_bulk
    queues: "emailsend_bulk"
    worker: 4
  - name: search
    queues: "searchindex"
    worker: 4
  - name: celery_solo_1
    queues: "redact,ocr"
    worker: 1
    type: slow
  - name: celery_solo_2
    queues: "redact,ocr,convert,convert_office,document"
    worker: 1
    type: slow
  - name: celery_solo_3
    queues: "redact,document"
    worker: 2
    type: slow

## in secrets.yml
# rabbitmq_admin_password:
rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
## in secrets.yml
# rabbitmq_application_password: from secrets
rabbitmq_node: "rabbit@localhost"

# This needs tessdata/ for tesseract >= 4 starting Ubuntu 18.04
tesseract_data_path: /usr/share/tesseract-ocr/4.00/tessdata/

dovecot_passwdfile_scheme: "sha512-crypt"

## in secrets.yml
# email_accounts:
#   - user: mail@fragdenstaat.de
#     password: "password"
#   - user: mail@fragdenstaat.de
#     password: "password"

email_host: "mail.fragdenstaat.de"
## in secrets.yml
# email_host_user: "mail@fragdenstaat.de"
# email_host_password: password
foi_email_host: "mail.fragdenstaat.de"
## in secrets.yml
# foi_email_host_user: "mail@fragdenstaat.de"
# foi_email_host_password: password
bounce_email_host: "mail.fragdenstaat.de"
## in secrets.yml
# bounce_email_host_user: "mail@fragdenstaat.de"
# bounce_email_host_password: password
unsubscribe_email_host: "mail.fragdenstaat.de"
## in secrets.yml
# unsubscribe_email_host_user: "mail@fragdenstaat.de"
# unsubscribe_email_host_password: password

## in secret.yml
# email_alias:
#   - from: "test@fragdenstaat.de"
#     to: "root@fragdenstaat.de"

## in secret.yml
alias_foi_domains: []

## in secret.yml
bad_referrers: []

## in secret.yml
# backup_ftp_url: "ftp://user@server"
# backup_ftp_password: "password"
# backup_gpg_password: "password"
# backup_cron_email:

nginx_static_dir: "/var/www/fragdenstaat.de/public/static/"
nginx_media_dir: "/var/www/fragdenstaat.de/storage"
nginx_private_media_path: "/var/www/fragdenstaat.de/storage/"

nginx_assets_dir:
  - url: "/assets/contractor/"
    dir: "files/contractor/"

nginx_public_media:
  - url: "/files/legalaction/"
  - url: "/files/media/"
  - url: "/files/profile/"
  - url: "/files/orglogo/"
  - url: "/files/docs/"
    force_download: true
  - url: "/files/datashow/"
    force_download: true

nginx_public_privileged_media:
  - "/files/campaign/"

nginx_private_media:
  - url: "/protected"
    dir: "files"
    force_download: true
  - url: "/private_main"
    dir: "private/main"
  - url: "/private_thumbnails"
    dir: "private/thumbnails"
  - url: "/filingcabinet-private"
    dir: "files"

nginx_private_media_prefix:
  - url: "/files/foi/"
  - url: "/files/docs-private/"
  - url: "/files/export/"
  - url: "/smedia"

redirect_domains:
  - from: "blog.fragdenstaat.de"
    domain: "fragdenstaat.de/blog"
    https: true
  - from: "shop.fragdenstaat.de"
    domain: "fragdenstaat.de/shop"
    https: true
  - from: "app.fragdenstaat.de"
    domain: "fragdenstaat.de/app/scanner/deep"
    https: true
    simple_files:
      - path: "/.well-known/apple-app-site-association"
        filename: apple-app-site-association
        mimetype: "application/json"
      - path: "/.well-known/assetlinks.json"
        filename: assetlinks.json
        mimetype: "application/json"
  - from: "mail.fragdenstaat.de"
    domain: "fragdenstaat.de"
    https: true
  - from: "media.frag-den-staat.de"
    domain: "media.frag-den-staat.de"
    https: false
  - from: "static.frag-den-staat.de"
    domain: "static.frag-den-staat.de"
    https: false
  - from: "verklagdenstaat.de"
    domain: "fragdenstaat.de/klagen"
    https: true
  - from: "zerschlagdenstaat.de"
    domain: "fragdenstaat.de"
    https: true
  - from: "frag-den-staat.de"
    domain: "fragdenstaat.de"
    https: true
  - from: "www.frag-den-staat.de"
    domain: "fragdenstaat.de"
    https: true

certbot_mode: "http-01"

## in secret.yml
temp_redirect_paths: []
valid_referrers: []

redirect_paths:
  - from: "^/files/foi/30800/"
    path: "/media-30800/"
  - from: "^/de/"
    path: "/"
  - from: "^/r/"
    path: "/a/"
  - from: "/blog/feed/"
    path: "/artikel/feed/"
  - from: "^/des/?$"
    path: "/dossier/desiderius-erasmus-stiftung/?pk_campaign=zdfmr"

media_legal_paths: []
# - path: "/files/foi/110867/bfr-stellungnahme.pdf"
#   link: "https://fragdenstaat.de/zensurheberrecht"

media_redirect_paths:
  - from: "/files/media/main/2e/bc/2ebc2ed7-51e4-4717-9fc7-a34225bebc5c/sog-masterplan-csu.pdf"
    path: "https://fragdenstaat.de/dokumente/30-sog-masterplan-csu/"
# - from: "/files/foi/110867/bfr-stellungnahme.pdf"
#   path: "https://fragdenstaat.de/dokumente/66/"

## in secret.yml
simple_files:
  - path: "/robots.txt"
    filename: robots.txt
  - path: "/.well-known/security.txt"
    filename: security.txt
  - path: "/.well-known/apple-app-site-association"
    filename: apple-app-site-association
    mimetype: "application/json"
  - path: "/.well-known/apple-developer-merchantid-domain-association"
    filename: apple-developer-merchantid-domain-association.dms
  - path: "/.well-known/assetlinks.json"
    filename: assetlinks.json
    mimetype: "application/json"
  - path: "/BingSiteAuth.xml"
    filename: BingSiteAuth.xml
  - filename: mta-sts.txt

cors_exceptions:
  - url: "/api/v1/campaigninformationobject"
    origins:
      - "__static__"
      - "__media__"
      - "https://okfde.github.io"

# CSP supports __wsweb__ __web__, __media__ and __static__ variable__s

content_security_policy:
  "default-src": "'none'"
  "script-src": "'self' __static__ https://traffic.okfn.de https://js.stripe.com"
  "style-src": "'self' 'unsafe-inline' __static__"
  "img-src": "'self' data: blob: __static__ __media__ https://traffic.okfn.de *.tile.openstreetmap.org *.global.ssl.fastly.net i.ytimg.com"
  "media-src": "__static__ __media__"
  "worker-src": "'self' blob: __static__"
  "frame-src": "'self' blob: __static__ __media__ https://www.youtube-nocookie.com https://media.ccc.de https://js.stripe.com https://hooks.stripe.com https://www.paypal.com https://datawrapper.dwcdn.net"
  "object-src": "'self' __media__"
  "connect-src": "'self' __wsweb__ __static__ __media__ https://sentry.okfn.de https://api.stripe.com https://traffic.okfn.de"
  "child-src": "'self' blob: __static__"
  "base-uri": "'none'"
  "font-src": "data: __static__"
  "manifest-src": "__static__"
  "form-action": "'self' __web__ https://forum.okfn.de https://www.paypal.com https://pretix.eu https://hooks.stripe.com https://stripe.com https://r.girogate.de"
  "report-uri": "https://sentry.okfn.de/api/3/security/?sentry_key=f00c20a879414df69051163a90597a8c"

## in secret.yml
content_security_policy_overrides:
  - url: "~^/account/authorize/"
    directives:
      "form-action": "* fragdenstaat:"

static_content_security_policy:
  - "default-src 'self' data: blob: __web__ __media__"
  - "style-src 'self' data: 'unsafe-inline'"
  - "connect-src 'self' __wsweb__ __web__ __media__"
  - "frame-ancestors *"
  - "report-uri https://sentry.okfn.de/api/3/security/?sentry_key=f00c20a879414df69051163a90597a8c"

media_content_security_policy:
  - "default-src 'none'"
  - "style-src 'unsafe-inline'"
  - "object-src 'self'"
  - "img-src 'self'"
  - "connect-src 'self'"
  - "media-src 'self'"
  - "frame-ancestors *"
  - "report-uri https://sentry.okfn.de/api/3/security/?sentry_key=f00c20a879414df69051163a90597a8c"

priviliged_media_content_security_policy:
  - "default-src 'self' data: __static__"
  - "script-src 'self' 'unsafe-inline' __static__ https://traffic.okfn.de"
  - "style-src 'self' 'unsafe-inline' __static__"
  - "img-src 'self' data: blob: __static__ https://traffic.okfn.de *.tile.openstreetmap.org *.global.ssl.fastly.net"
  - "worker-src 'self' blob: __static__"
  - "frame-src 'self' blob: __static__ __web__ https://www.youtube-nocookie.com https://media.ccc.de"
  - "object-src 'self' __web__"
  - "connect-src 'self' __web__ __wsweb__"
  - "child-src blob: __static__"
  - "frame-ancestors *"
  - "report-uri https://sentry.okfn.de/api/3/security/?sentry_key=f00c20a879414df69051163a90597a8c"

nginx_extra_domains:
  - domain: mta-sts.fragdenstaat.de
    files:
      - path: "/.well-known/mta-sts.txt"
        filename: mta-sts.txt

## in secrets.yml
django_sentry_dsn: ""
django_sentry_public_dsn: ""
sentry_auth_token: ""
sentry_url: ""
sentry_org: ""
sentry_project: ""
sentry_webhook_url: ""

matomo_site_id: "25"

yelp_api_key: ""
foursquare_api_key: ""
mapbox_api_key: ""
google_places_api_key: ""
here_geocode_api_key: ""

telnyx_app_id: ""
telnyx_api_key: ""
telnyx_public_key: ""
telnyx_from_number: ""

stripe_public_key: ""
stripe_private_key: ""
stripe_webhook_cc_signing_key: ""
stripe_webhook_sepa_signing_key: ""
stripe_webhook_sofort_signing_key: ""

paypal_client_id: ""
paypal_client_secret: ""
paypal_api_url: ""
paypal_webhook_id: ""

slack_webhook_url: ""
matomo_api_url: ""

geoip_account_id: 0
geoip_license_key: ""
suspicious_asn_list: ""

fds_legal_backup_credentials: ""
fds_legal_backup_url: ""

donation_backup_url: ""
donation_backup_credentials: ""

paperless_api_url: ""
paperless_api_token: ""
paperless_uploaded_type: ""
paperless_request_field: ""

froide_evidencecollection_nocodb_api_token: ""
froide_evidencecollection_nocodb_api_url: ""
froide_evidencecollection_nocodb_evidence_table: ""
froide_evidencecollection_nocodb_group_table: ""
froide_evidencecollection_nocodb_person_table: ""
froide_evidencecollection_nocodb_source_table: ""
