---

# - name: Add the RabbitMQ public GPG key to the apt repo
#   ansible.builtin.apt_key:
#     url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
#     state: present

# - name: Add RabbitMQ to the sources list
#   ansible.builtin.apt_repository:
#     repo: 'deb https://www.rabbitmq.com/debian/ testing main'
#     update_cache: "{{ update_apt_cache }}"
#     state: present

- name: Install RabbitMQ server
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: "{{ update_apt_cache }}"
    force: true
    state: present
  with_items:
    - rabbitmq-server

- name: Enable the RabbitMQ Management Console
  community.rabbitmq.rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  notify: restart rabbitmq-server

- name: Ensure that the RabbitMQ service is running
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: true

- name: Import setup_vhosts.yml
  ansible.builtin.import_tasks: setup_vhosts.yml

- name: Import setup_users.yml
  ansible.builtin.import_tasks: setup_users.yml
