---

base_timezone: Europe/Berlin

server_user: root

enable_unattended_upgrades: true

enable_ufw: true

enable_fail2ban: true

unattended_calendar: "*-*-* 6:00"
unattended_delay: "60m"

apt_update_cache: true
base_packages_latest:
  - bash
  - openssl
  - libssl-dev
  - libssl-doc

base_packages_install:
  - acl
  - bc
  - bind9-host
  - build-essential
  - gpg
  - gpg-agent
  - man
  - ntpsec
  - ntpsec-ntpdate
  - vim

base_packages_remove: []

needrestart:
  ignorelist:
    - "postgres.*"
    - "postfix[.]service"
    - "libvirtd[.]service"
    - "docker[.]service"
    - "containerd[.]service"
