---

base_ssh_port: 22

base_timezone: Europe/Berlin

base_enable_unattended_upgrades: true

base_enable_ufw: true

base_enable_fail2ban: true

base_unattended_calendar: "*-*-* 6:00"
base_unattended_delay: "60m"

base_create_swap_file: false
base_swap_file_path: /swapfile
base_swap_file_size_kb: 512

base_apt_update_cache: "{{ update_apt_cache | default('true') }}"

base_packages_latest:
  - bash
  - openssl
  - libssl-dev
  - libssl-doc

base_packages_install:
  - acl
  - bc
  - bind9-host
  - build-essential
  - gpg
  - gpg-agent
  - man
  - ntpsec
  - ntpsec-ntpdate
  - vim

base_packages_remove: []

base_needrestart:
  ignorelist:
    - "postgres.*"
    - "postfix[.]service"
    - "libvirtd[.]service"
    - "docker[.]service"
    - "containerd[.]service"
