- name: Base
  hosts: all
  become: true
  become_user: root
  vars_files:
    - ../local_vars/local_config.yml

  vars_prompt:
    - name: user_name
      prompt: "Name of the user?"
      private: false

  tasks:
    - name: Remove user
      ansible.builtin.user:
        name: "{{ user_name }}"
        state: absent
