---

- name: Create virtual machine via vagrant for {{ application_name }}
  hosts: all
  become: true
  remote_user: root
#  vars_files:
#    - env_vars/vagrant.yml

  roles:
    - base
    - db
    - memcached
    # - rabbitmq
    - elasticsearch
    - redis
    - app
    - appserver
    - celery
    # # - certbot
    - nginx
