---
- name: Add VPN client
  hosts: localhost
  connection: local
  vars_prompt:
    - name: client_name
      prompt: "Name of the client?"
      private: false

  tasks:
    - name: Generate new private key locally
      ansible.builtin.command:
        cmd: "wg genkey"
      delegate_to: localhost
      register: private_key
      changed_when: true

    - name: Generate new public key locally
      ansible.builtin.command:
        cmd: wg pubkey
        stdin: "{{ private_key.stdout }}"
      delegate_to: localhost
      register: public_key
      changed_when: true

    - name: Include role vars
      ansible.builtin.include_vars: "../roles/wireguard/defaults/main.yml"

    - name: Load vpn client list
      ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
      vars:
        params:
          files:
            - vpnclients.yml
            - vpnclients-default.yml
          paths:
            - "../env_vars"

    - name: Find max VPN peer id
      ansible.builtin.set_fact:
        max_peer_id: "{{ vpn_clientgroups.0.peers | map(attribute='peer_id') | max }}"

    - name: Set new VPN peer id
      ansible.builtin.set_fact:
        peer_id: "{{ max_peer_id | int | default(0) + 1 }}"

    - name: Fail when peer id too large
      ansible.builtin.fail:
        msg: "Peer id {{ peer_id }} too large! Please cleanup client list or set peer id manually!"
      when: peer_id | int >= 200

    - name: Make peer config
      ansible.builtin.template:
        src: "../roles/wireguard/templates/client.conf.j2"
        dest: "../FDS_VPN_{{ client_name }}.conf"
        mode: "0640"
      delegate_to: localhost

    - name: Store peer config
      ansible.builtin.template:
        src: "../roles/wireguard/templates/clientgroups.yml.j2"
        dest: "../env_vars/vpnclients.yml"
        mode: "0640"
      delegate_to: localhost

    - name: Encrypt vpn client list
      ansible.builtin.command:
        cmd: "ansible-vault encrypt --vault-password-file ../vault.key ../env_vars/vpnclients.yml"
      delegate_to: localhost
      changed_when: true

    - name: Print public key
      ansible.builtin.debug:
        var: public_key.stdout
