---

- name: Install duplicity dependencies
  ansible.builtin.apt:
    name:
      - librsync-dev
      - lftp
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags: packages
  retries: 30
  delay: 10

- name: Install duplicity from pip
  ansible.builtin.pip:
    name: duplicity
    state: latest
  become: true

- name: Do not verify SSL certificate
  ansible.builtin.lineinfile:
    path: /etc/lftp.conf
    line: "set ssl:verify-certificate no"

- name: Create the folder for the backup files
  ansible.builtin.file:
    path: "{{ virtualenv_path }}/backup"
    owner: root
    state: directory
    mode: "0755"
  tags: backup

- name: Place backup script
  ansible.builtin.template:
    src: backup.sh.j2
    dest: /usr/local/bin/backup.sh
    mode: "0600"
  tags: backup

- name: Setup cron script
  ansible.builtin.cron:
    name: "Run backup script"
    minute: "0"
    hour: "5"
    job: "sh /usr/local/bin/backup.sh"

- name: set mailto env in cron
  ansible.builtin.cron:
    user: root
    name: MAILTO
    env: true
    value: "{{ backup_cron_email }}"
  when: backup_cron_email is defined and backup_cron_email
  tags:
    - cron

- name: Create custom backup log rotation file
  ansible.builtin.template:
    src: fds_backup_logrotate.j2
    dest: "/etc/logrotate.d/{{ application_name }}_backup"
    mode: "0600"
    backup: true
