---

- name: Install duplicity dependencies
  apt:
    name:
      - librsync-dev
      - lftp
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags: packages

- name: Install duplicity from pip
  pip:
    name: duplicity
    state: latest
  become: true

- name: Do not verify SSL certificate
  lineinfile:
    path: /etc/lftp.conf
    line: "set ssl:verify-certificate no"

- name: Create the folder for the backup files
  file:
    path: "{{ virtualenv_path }}/backup"
    owner: root
    state: directory
  tags: backup

- name: Place backup script
  template:
    src: backup.sh.j2
    dest: /usr/local/bin/backup.sh
  tags: backup

- name: Setup cron script
  cron:
    name: "Run backup script"
    minute: "0"
    hour: "5"
    job: "sh /usr/local/bin/backup.sh"

- name: set mailto env in cron
  cron:
    user: root
    name: MAILTO
    env: yes
    value: "{{ backup_cron_email }}"
  when: backup_cron_email is defined and backup_cron_email
  tags:
    - cron

- name: Create custom backup log rotation file
  template:
    src: fds_backup_logrotate.j2
    dest: "/etc/logrotate.d/{{ application_name }}_backup"
    backup: yes
