---

- name: Install duplicity dependencies
  ansible.builtin.apt:
    name:
      - librsync-dev
      - lftp
      - duplicity
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags: packages
  retries: 30
  delay: 10

- name: Do not verify SSL certificate
  ansible.builtin.lineinfile:
    path: /etc/lftp.conf
    line: "set ssl:verify-certificate no"

- name: Create the folder for the backup files
  ansible.builtin.file:
    path: "/var/backup/sentry"
    owner: root
    state: directory
    mode: "0755"
  tags: backup

- name: Place backup script
  ansible.builtin.template:
    src: backup.sh.j2
    dest: /usr/local/bin/backup_sentry.sh
    mode: "0755"
  tags: backup

- name: Setup cron script
  ansible.builtin.cron:
    name: "Run backup sentry script"
    minute: "0"
    hour: "20"
    job: "bash /usr/local/bin/backup_sentry.sh"
  when: "not 'tst.okfn.de' in inventory_hostname"
