---

postfix_hostname: "fds-smtp1.zerschlagdenstaat.de"
postfix_reject_helo_list: []

dkim_domains:
  - name: fds-smtp1.zerschlagdenstaat.de
    selector: mail
    keysize: 4096
dkim_admin_mail: postmaster@zerschlagdenstaat.de

dmarc_admin_mail: "postmaster@zerschlagdenstaat.de"
dmarc_org: zerschlagdenstaat.de

rspamd: true
rspamd_modules:
  - arc
  - dkim_signing
  - dkim
  - dmarc
  - spf
rspamd_worker:
  - proxy
  - controller
rspamd_url: rspamd1.zerschlagdenstaat.de
