{
 "title": "Ansible",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "task",
    "label": "playbook",
    "query": {
     "query": "label_values(ansible_changed,task)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ansible_totaltime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ok",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ansible_ok)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "changed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ansible_changed)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ansible_failed)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "unreachable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ansible_unreachable)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "skipped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ansible_skipped)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ignored",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ansible_ignored)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "rescued",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ansible_rescued)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ansible_changed)", "legendFormat": "changed" },
    { "expr": "sum(ansible_failed)", "legendFormat": "failed" },
    { "expr": "sum(ansible_ignored)", "legendFormat": "ignored" },
    { "expr": "sum(ansible_ok)", "legendFormat": "ok" },
    { "expr": "sum(ansible_skipped)", "legendFormat": "skipped" },
    { "expr": "sum(ansible_rescued)", "legendFormat": "rescued" },
    { "expr": "sum(ansible_unreachable)", "legendFormat": "unreachable" }
   ]
  },
  {
   "title": "Status by host",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "tasks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(hostname)(ansible_changed)",
     "legendFormat": "changed-{{hostname}}"
    },
    {
     "expr": "sum by(hostname)(ansible_failed)",
     "legendFormat": "failed-{{hostname}}"
    },
    {
     "expr": "sum by(hostname)(ansible_ignored)",
     "legendFormat": "ignored-{{hostname}}"
    },
    { "expr": "sum by(hostname)(ansible_ok)", "legendFormat": "ok-{{hostname}}" },
    {
     "expr": "sum by(hostname)(ansible_skipped)",
     "legendFormat": "skipped-{{hostname}}"
    },
    {
     "expr": "sum by(hostname)(ansible_rescued)",
     "legendFormat": "rescued-{{hostname}}"
    },
    {
     "expr": "sum by(hostname)(ansible_unreachable)",
     "legendFormat": "unreachable-{{hostname}}"
    }
   ]
  },
  { "title": "./playbooks/$task.yml", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "task" },
  {
   "title": "OK $task",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "ansible_ok{task=~\"$task\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Changed $task",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "ansible_changed{task=~\"$task\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Failed $task",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "ansible_failed{task=~\"$task\"}",
     "legendFormat": "failed {{hostname}}"
    },
    {
     "expr": "ansible_unreachable{task=~\"$task\"}",
     "legendFormat": "unreachable {{ hostname }}"
    }
   ]
  },
  {
   "title": "Skipped $task",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "ansible_skipped{task=~\"$task\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Rescued $task",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "ansible_rescued{task=~\"$task\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Ignored $task",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "ansible_ignored{task=~\"$task\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}