{
 "title": "Borg Backup",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(borg_total_chunks,hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Repository Info for $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "borg_unique_size{hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Backup Duration",
   "type": "barchart",
   "gridPos": { "h": 23, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "borg_Createbackup_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Backup"
    },
    {
     "expr": "borg_Prunebackupgenerations_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Prune"
    },
    {
     "expr": "borg_BackupCheckquickfirst_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Check (quick, first)"
    },
    {
     "expr": "borg_BackupInfo_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Get Repo Info"
    },
    {
     "expr": "borg_BackupList_seconds{hostname=\"$hostname\"}",
     "legendFormat": "List Repo Info"
    },
    {
     "expr": "borg_Createmountpoints_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Create Mountpoints"
    },
    {
     "expr": "borg_Removinglock_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Remove Lock"
    },
    {
     "expr": "borg_Umountandremovesnapshots_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Remove Snapshots"
    },
    {
     "expr": "borg_Postscriptpurge_local_backups_sh_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Postscript: local purge"
    },
    {
     "expr": "borg_Prescriptcreate_postgres_backup_sh_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Prescript: Postgres"
    },
    {
     "expr": "borg_Prescriptdpkg_get_selections_sh_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Prescript: dpkg selections"
    },
    {
     "expr": "borg_Prescriptmetabase_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Prescript: metabase"
    },
    {
     "expr": "borg_Prescriptnocodb_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Prescript: nocodb"
    },
    {
     "expr": "borg_ExportRepokey_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Export repokey"
    },
    {
     "expr": "borg_BackupCheckquicklast_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Check (quick, last)"
    },
    {
     "expr": "borg_BackupCheckquick_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Check (quick)"
    },
    {
     "expr": "borg_BackupCheckverify_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Check (verify)"
    }
   ]
  },
  {
   "title": "Backup duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "borg_total_time_seconds{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last modified",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "borg_last_modified{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storagebox Diskspace",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "borg_unique_csize{hostname=\"$hostname\"} / 1000",
     "legendFormat": "This repo"
    },
    {
     "expr": "borg_storagebox_used{hostname=\"$hostname\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "borg_storagebox_avail{hostname=\"$hostname\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Repo size",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "borg_unique_csize{hostname=\"$hostname\"}",
     "legendFormat": "Deduplicated"
    },
    {
     "expr": "borg_total_csize{hostname=\"$hostname\"}",
     "legendFormat": "Compressed"
    },
    {
     "expr": "borg_total_size{hostname=\"$hostname\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Location",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "borg_info{hostname=\"$hostname\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Repository ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "borg_info{hostname=\"$hostname\"}",
     "legendFormat": "{{repository_id}}"
    }
   ]
  },
  { "title": "Repository Stats for $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "hostname" },
  {
   "title": "Chunks",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "avg(borg_total_chunks{hostname=\"$hostname\"})",
     "legendFormat": "Total chunks"
    },
    {
     "expr": "avg(borg_total_unique_chunks{hostname=\"$hostname\"})",
     "legendFormat": "Deduplicated chunks"
    }
   ]
  },
  {
   "title": "Size",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(borg_total_size{hostname=\"$hostname\"})",
     "legendFormat": "Total size"
    },
    {
     "expr": "avg(borg_unique_size{hostname=\"$hostname\"})",
     "legendFormat": "Deduplicated size"
    }
   ]
  },
  {
   "title": "Compressed Size",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(borg_total_csize{hostname=\"$hostname\"})",
     "legendFormat": "Total compressed size"
    },
    {
     "expr": "avg(borg_unique_csize{hostname=\"$hostname\"})",
     "legendFormat": "Deduplicated compressed size"
    }
   ]
  },
  { "title": "Ratios for $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 }, "repeat": "hostname" },
  {
   "title": "Deduplication Ratio",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(borg_total_size{hostname=\"$hostname\"})",
     "legendFormat": "Total size"
    },
    {
     "expr": "avg(borg_unique_csize{hostname=\"$hostname\"})",
     "legendFormat": "Deduplicated size"
    }
   ]
  },
  {
   "title": "Compression Ratio",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(borg_total_size{hostname=\"$hostname\"})",
     "legendFormat": "Total size"
    },
    {
     "expr": "avg(borg_total_csize{hostname=\"$hostname\"})",
     "legendFormat": "Compressed size"
    }
   ]
  }
 ]
}