{
 "title": "NFS",
 "tags": [
  "nfs",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_boot_time_seconds, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_nfs_rpcs_total{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_boot_time_seconds{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "NFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NFS RPC",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfs_rpc_authentication_refreshes_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Number of RPC authentication refreshes performed"
    },
    {
     "expr": "rate(node_nfs_rpc_retransmissions_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Number of RPC transmissions performed"
    },
    {
     "expr": "rate(node_nfs_rpcs_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Total number of RPCs performed"
    }
   ]
  },
  { "title": "NFS v4 Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "NFS v4 NFS Procedures Invoked 1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfs_requests_total{method='Access',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Commit',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Create',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='FsInfo',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='GetAttr',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Link',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Lookup',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Null',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Allocate',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='BindConnToSession',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Clone',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "NFS v4 NFS Procedures Invoked 2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfs_requests_total{method='PathConf',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Read',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='ReadDir',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='ReadLink',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Rename',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Setattr',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='SymLink',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Write',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Close',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='CreateSession',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Read',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "NFS v4 NFS Procedures Invoked 3",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfs_requests_total{method='DeAllocate',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='DelegReturn',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='DestroyClientID',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='DestroySession',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='ExchangeID',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='FreeStateID',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='FsLocations',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='FsidPresent',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='GetACL',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='GetDeviceInfo',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "NFS v4 NFS Procedures Invoked 4",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfs_requests_total{method='GetDeviceList',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='GetLeaseTime',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='LayoutCommit',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='LayoutGet',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='LayoutReturn',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='LayoutStats',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Lock',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Lockt',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Locku',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Lookup',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "NFS v4 NFS Procedures Invoked 5",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfs_requests_total{method='LookupRoot',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Open',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='OpenConfirmt',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='OpenDowngrade',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='OpenNoattr',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='ReclaimComplete',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='ReleaseLockowner',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Renew',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Secinfo',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='SecinfoNoName',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "NFS v4 NFS Procedures Invoked 6",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfs_requests_total{method='Seek',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='Sequence',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='ServerCaps',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='SetACL',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='SetClientID',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='SetClientIDConfirm',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='StatFs',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfs_requests_total{method='TestStateID',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    }
   ]
  }
 ]
}