{
 "title": "postgres replication status",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "postgres_replication_active" } }
  ]
 },
 "panels": [
  {
   "title": "slot_name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "postgres_replication_delta{slot_name=\"$instance\"}",
     "legendFormat": "{{slot_name}}"
    }
   ]
  },
  {
   "title": "slot_type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "postgres_replication_slot_type{slot_name=\"$instance\"}",
     "legendFormat": "{{slot_type}}"
    }
   ]
  },
  {
   "title": "active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "postgres_replication_active{slot_name=\"$instance\"}",
     "legendFormat": "{{active}}"
    }
   ]
  },
  {
   "title": "delta_pretty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "postgres_replication_delta_pretty{slot_name=\"$instance\"}",
     "legendFormat": "{{delta_pretty}}"
    }
   ]
  },
  {
   "title": "unit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "postgres_replication_unit{slot_name=\"$instance\"}",
     "legendFormat": "{{unit}}"
    }
   ]
  },
  {
   "title": "slot_lsn",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "postgres_replication_slot_lsn{slot_name=\"$instance\"}",
     "legendFormat": "{{slot_lsn}}"
    }
   ]
  },
  {
   "title": "Postgres Replication Delta",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "postgres_replication_delta{slot_name=\"$instance\"}",
     "legendFormat": "{{slot_name}}"
    }
   ]
  }
 ]
}