{
 "title": "Nginx",
 "tags": [
  "nginx",
  "graylog"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Top 10 IPs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "application_name: nginx",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 10 URLs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 13, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "application_name: nginx",
     "timeField": "filebeat_@timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Status Codes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "status",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "application_name: nginx",
     "timeField": "filebeat_@timestamp"
    }
   ]
  },
  {
   "title": "Top 10 User Agents",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "useragent",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "application_name: nginx",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Referer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "referer",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "application_name: nginx",
     "timeField": "filebeat_@timestamp"
    }
   ]
  },
  {
   "title": "Top Request Types",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "requesttype",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "application_name: nginx",
     "timeField": "filebeat_@timestamp"
    }
   ]
  },
  {
   "title": "Log entries over time",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "Hits",
     "bucketAggs": [
      {
       "field": "filebeat_@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "filebeat_log_file_path:\"/var/www/fragdenstaat.de/logs/nginx_access.log\"",
     "timeField": "filebeat_@timestamp"
    },
    {
     "alias": "Error",
     "bucketAggs": [
      { "field": "filebeat_@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "filebeat_log_file_path:\"/var/www/fragdenstaat.de/logs/nginx_error.log\"",
     "timeField": "filebeat_@timestamp"
    }
   ]
  },
  {
   "title": "Nginx Access Log",
   "type": "table",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "filebeat_log_file_path:\"/var/www/fragdenstaat.de/logs/nginx_access.log\" AND application_name: nginx",
     "timeField": "filebeat_@timestamp"
    }
   ]
  },
  {
   "title": "Nginx Error Log",
   "type": "table",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "filebeat_log_file_path:\"/var/www/fragdenstaat.de/logs/nginx_error.log\"",
     "timeField": "filebeat_@timestamp"
    }
   ]
  }
 ]
}