---

- name: Create the folder for the celery scripts
  ansible.builtin.file: path={{ celery_scripts_dir }}
        owner={{ celery_user }}
        group={{ celery_group }}
        mode=0774
        state=directory
  tags:
    - celery

- name: Create the celery worker script file
  ansible.builtin.template:
    src: celery_worker.j2
    dest: "{{ celery_scripts_dir }}/celery_{{ item.name }}"
    owner: "{{ celery_user }}"
    group: "{{ celery_group }}"
    mode: "0755"
  with_items: "{{ celery_workers }}"
  tags:
    - celery

- name: Create the celery beat script file
  ansible.builtin.template:
    src: "{{ celerybeat_template_file }}"
    dest: "{{ celery_scripts_dir }}/celerybeat_start"
    owner: "{{ celery_user }}"
    group: "{{ celery_group }}"
    mode: "0755"
  tags:
    - celery
