---

- import_tasks: copy_scripts.yml

- import_tasks: setup_supervisor.yml

- name: Update celery workers
  community.general.supervisorctl:
    name: "celery_{{ item.name }}"
    state: restarted
  with_items: "{{ celery_workers }}"
  tags:
    - celery
    - deploy
    - deploy-backend
  changed_when: false

- name: Update celery beat
  community.general.supervisorctl:
    name: celerybeat
    state: restarted
  tags:
    - celery
    - deploy
    - deploy-backend
  changed_when: false
