---

- import_tasks: copy_scripts.yml

- import_tasks: setup_supervisor.yml

- name: Restart the celery workers
  supervisorctl:
    name: celery_{{ item.name }}
    state: restarted
  with_items: "{{ celery_worker }}"
  tags:
    - celery
    - deploy
    - deploy-backend

- name: Restart the {{ celerybeat_application_name }} app
  supervisorctl: name={{ celerybeat_application_name }} state=restarted
  tags:
    - celery
    - deploy
    - deploy-backend

- name: Check running applications managed by supervisor
  shell: supervisorctl status
  tags:
    - celery
    - deploy
    - deploy-backend
