---

- import_tasks: copy_scripts.yml

- import_tasks: setup_supervisor.yml


- name: Update celery workers
  community.general.supervisorctl:
    name: "{{ item.name }}"
    state: restarted
  with_items: "{{ celery_worker }}"
  tags:
    - celery
    - deploy
    - deploy-backend

- name: Update celery beat
  community.general.supervisorctl:
    name: celerybeat
    state: restarted
  with_items: "{{ celery_worker }}"
  tags:
    - celery
    - deploy
    - deploy-backend
