---

- name: Create the Supervisor config file for celery workers
  ansible.builtin.template:
    src: supervisor_celery.conf.j2
    dest: "/etc/supervisor/conf.d/{{ item.name }}.conf"
    mode: "0600"
  with_items: "{{ celery_workers }}"
  tags:
    - celery

- name: Create the Supervisor config file for celerybeat
  ansible.builtin.template:
    src: supervisor_celerybeat.conf.j2
    dest: /etc/supervisor/conf.d/celerybeat.conf
    mode: "0600"
  tags:
    - celery

- name: Create the celery log directory
  ansible.builtin.file:
    path: "{{ celery_log_dir }}"
    owner: "{{ celery_user }}"
    group: "{{ celery_group }}"
    state: "directory"
    mode: "0774"
  tags:
    - celery

- name: Check if celery worker log files exists
  ansible.builtin.stat:
    path: "{{ celery_log_dir }}/celery_{{ item.name }}.log"
  register: worker_logs
  with_items: "{{ celery_workers }}"

- name: Create the celery worker log files
  ansible.builtin.file:
    path: "{{ celery_log_dir }}/celery_{{ item.0.name }}.log"
    owner: "{{ celery_user }}"
    group: "{{ celery_group }}"
    state: "touch"
    mode: "0644"
  with_nested:
    - "{{ celery_workers }}"
    - "{{ worker_logs.results }}"
  tags:
    - celery
  when: "not item.1.stat.exists"

- name: Check if celery beat log files exists
  ansible.builtin.stat:
    path: "{{ celerybeat_log_file }}"
  register: beat_log

- name: Create the celery beat application log file
  ansible.builtin.file:
    path: "{{ celerybeat_log_file }}"
    owner: "{{ celery_user }}"
    group: "{{ celery_group }}"
    state: "touch"
    mode: "0644"
  tags:
    - celery
  when: "not beat_log.stat.exists"

- name: Add celery workers
  community.general.supervisorctl:
    name: "celery_{{ item.name }}"
    state: present
  with_items: "{{ celery_workers }}"

- name: Add celery beat
  community.general.supervisorctl:
    name: celerybeat
    state: present
  with_items: "{{ celery_workers }}"
