- name: Create nocodb directory
  ansible.builtin.file:
    state: directory
    path: "{{ nc_dir }}"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create data directory
  ansible.builtin.file:
    state: directory
    path: "{{ nc_dir }}/data"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create database directory
  ansible.builtin.file:
    state: directory
    path: "{{ nc_dir }}/data/db"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create database directory
  ansible.builtin.file:
    state: directory
    path: "{{ nc_dir }}/data/db"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ nc_dir }}/docker-compose.yml"
    mode: "0640"
    owner: "root"
    group: "root"
  notify: docker compose up nocodb

- name: Create nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-enabled/nocodb.conf"
    mode: "0640"
    owner: "root"
    group: "root"
  notify: restart nginx

- name: debug
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_items: "{{ nc_db_brooke }}"
  tags: debug

- name: Create additional databases on brooke
  community.general.postgresql_db:
    name: "{{ item.db_name }}"
    state: present
  delegate_to: "brooke.okfn.de"
  become: true
  become_user: postgres
  with_items: "{{ nc_db_brooke }}"

- name: Ensure user has access to the new database
  community.general.postgresql_user:
    name: "{{ item.db_user }}"
    password: "{{ item.db_pass }}"
    db: "{{ item.db_name }}"
    priv: "ALL"
    state: present
  delegate_to: "brooke.okfn.de"
  become: true
  become_user: postgres
  with_items: "{{ nc_db_brooke }}"

- name: Ensure user does not have unnecessary permissions
  community.general.postgresql_user:
    name: "{{ item.db_user }}"
    role_attr_flags: "NOSUPERUSER,NOCREATEDB"
    state: present
  delegate_to: "brooke.okfn.de"
  become: true
  become_user: postgres
  with_items: "{{ nc_db_brooke }}"
