- name: Enable Focal deb-src
  ansible.builtin.apt_repository:
    repo: deb-src http://de.archive.ubuntu.com/ubuntu focal main restricted
    state: present
  when: ansible_distribution_version == "20.04"

- name: Enable Focal deb-src
  ansible.builtin.apt_repository:
    repo: deb-src http://de.archive.ubuntu.com/ubuntu jammy main restricted
    state: present
  when: ansible_distribution_version == "22.04"

- name: Install the imagemagick
  ansible.builtin.apt:
    pkg: imagemagick
    state: present
  retries: 30
  delay: 10
