- name: Enable deb-src
  ansible.builtin.apt_repository:
    repo: "deb-src http://de.archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main restricted"
    state: present

- name: Install the imagemagick
  ansible.builtin.apt:
    pkg: imagemagick
    state: present
  retries: 3
  delay: 10
