---

- import_tasks: install_additional_packages.yml
  tags: packages

- import_tasks: create_users_and_groups.yml

- import_tasks: mount_media_storage.yml
  when: external_media_storage

- import_tasks: setup_virtualenv.yml
  tags: virtualenv

- import_tasks: install_latest_poppler.yml
  tags:
    - packages
    - poppler

- import_tasks: install_latest_imagemagick.yml
  tags:
    - packages

- import_tasks: setup_git_repo.yml
  tags:
    - deploy
    - deploy-backend
    - deploy-web
    - deploy-frontend

- import_tasks: set_file_permissions.yml

- import_tasks: setup_django_app.yml
  tags:
    - deploy
    - deploy-frontend
    - deploy-web
    - deploy-backend

- import_tasks: setup_geoip.yml
  when: geoip_license_key != ""

- import_tasks: run_django_tasks.yml
  tags:
    - deploy
    - deploy-backend
    - deploy-web
    - deploy-frontend

- name: release notifications
  import_tasks: release_notification.yml
  when: collect_release_info

# TODO: run through celery tasks
# - import_tasks: setup_cron_tasks.yml
#   tags: maintenance
