---

- name: Import install_additional_packages.yml
  ansible.builtin.import_tasks: install_additional_packages.yml
  tags: packages

- name: Import create_users_and_groups.yml
  ansible.builtin.import_tasks: create_users_and_groups.yml

- name: Import mount_media_storage.yml
  ansible.builtin.import_tasks: mount_media_storage.yml
  when: external_media_storage

- name: Import setup_virtualenv.yml
  ansible.builtin.import_tasks: setup_virtualenv.yml
  tags: virtualenv

- name: Import install_latest_poppler.yml
  ansible.builtin.import_tasks: install_latest_poppler.yml
  tags:
    - packages
    - poppler

- name: Import install_latest_imagemagick.yml
  ansible.builtin.import_tasks: install_latest_imagemagick.yml
  tags:
    - packages

- name: Import setup_git_repo.yml
  ansible.builtin.import_tasks: setup_git_repo.yml
  tags:
    - deploy
    - deploy-backend
    - deploy-web
    - deploy-frontend

- name: Import set_file_permissions.yml
  ansible.builtin.import_tasks: set_file_permissions.yml

- name: Import setup_django_app.yml
  ansible.builtin.import_tasks: setup_django_app.yml
  tags:
    - deploy
    - deploy-frontend
    - deploy-web
    - deploy-backend

- name: Import setup_geoip.yml
  ansible.builtin.import_tasks: setup_geoip.yml
  when: geoip_license_key|length > 0

- name: Import run_django_tasks.yml
  ansible.builtin.import_tasks: run_django_tasks.yml
  tags:
    - deploy
    - deploy-backend
    - deploy-web
    - deploy-frontend

- name: release notifications
  ansible.builtin.import_tasks: release_notification.yml
  when: collect_release_info

# TODO: run through celery tasks
# - import_tasks: setup_cron_tasks.yml
#   tags: maintenance
