---

- name: Setup release notification script
  template: src=notify-release.sh.j2 dest={{ virtualenv_path }}/notify-release.sh mode=0755
  tags:
    - release

- name: Run release notification
  command: "{{ virtualenv_path }}/notify-release.sh"
  become: true
  become_user: "{{ gunicorn_user }}"
  tags:
    - deploy
    - deploy-frontend
    - deploy-web
    - deploy-backend
