---

- name: Run Django database migrations
  django_manage:
    command: "migrate --noinput"
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  tags:
    - django.migrate
    - deploy-web
    - deploy-backend
  become: true
  become_user: "{{ gunicorn_user }}"

- name: Run Django compilemessages
  command: "{{ virtualenv_path }}/bin/python {{ virtualenv_path }}/fragdenstaat.de/manage.py compilemessages -l de"
  args:
    chdir: "{{ item }}"
  with_items:
    - "{{ virtualenv_path }}/src"
    - "{{ project_path }}"
  environment: "{{ django_environment }}"
  become: true
  become_user: "{{ gunicorn_user }}"
  tags:
    - django.compilemessages
    - deploy-web
    - deploy-backend
