---

- name: Save django db user name
  ansible.builtin.set_fact:
    django_environment_db_user: "{{ django_environment['DATABASE_USER'] }}"
  tags:
    - django.migrate
    - deploy-web
    - deploy-backend

- name: Save django db user password
  ansible.builtin.set_fact:
    django_environment_db_password: "{{ django_environment['DATABASE_PASSWORD'] }}"
  tags:
    - django.migrate
    - deploy-web
    - deploy-backend

- name: Overwrite django db user
  ansible.builtin.set_fact:
    django_environment: "{{ django_environment | combine({'DATABASE_USER': 'django_migrations'}) }}"
  tags:
    - django.migrate
    - deploy-web
    - deploy-backend

- name: Overwrite django db user password
  ansible.builtin.set_fact:
    django_environment: "{{ django_environment | combine({'DATABASE_PASSWORD': '{{ django_migrations_db_password }}'}) }}"
  tags:
    - django.migrate
    - deploy-web
    - deploy-backend

- name: Create postgres migrations user
  community.postgresql.postgresql_user:
    name: "django_migrations"
    password: "{{ django_migrations_db_password }}"
  tags:
    - django.migrate
    - deploy-web
    - deploy-backend
  become: true
  become_user: postgres

- name: Set migration user privs
  community.postgresql.postgresql_privs:
    db: "{{ db_name }}"
    role: django_migrations
    objs: ALL_IN_SCHEMA
    privs: ALL
    grant_option: true
  tags:
    - django.migrate
    - deploy-web
    - deploy-backend
  become: true
  become_user: postgres

- name: Set migration user privs (schema)
  community.postgresql.postgresql_privs:
    db: "{{ db_name }}"
    role: django_migrations
    objs: public
    privs: ALL
    grant_option: true
    type: schema
  tags:
    - django.migrate
    - deploy-web
    - deploy-backend
  become: true
  become_user: postgres

- name: Run Django database migrations
  community.general.django_manage:
    command: "migrate --noinput"
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  tags:
    - django.migrate
    - deploy-web
    - deploy-backend
  become: true
  become_user: "{{ gunicorn_user }}"
  ignore_errors: true

- name: Run Django compilemessages
  ansible.builtin.command: "{{ virtualenv_path }}/bin/python {{ virtualenv_path }}/fragdenstaat.de/manage.py compilemessages -l de"
  args:
    chdir: "{{ item }}"
  with_items:
    - "{{ virtualenv_path }}/src"
    - "{{ project_path }}"
  environment: "{{ django_environment }}"
  register: compile_result
  changed_when: "'processing file' in compile_result.stdout"
  become: true
  become_user: "{{ gunicorn_user }}"
  tags:
    - django.compilemessages
    - deploy-web
    - deploy-backend
  ignore_errors: true

- name: Restore django environment db user
  ansible.builtin.set_fact:
    django_environment: "{{ django_environment | combine({'DATABASE_USER': '{{ django_environment_db_user }}'}) }}"
  tags:
    - django.migrate
    - deploy-web
    - deploy-backend

- name: Restore django environment db user password
  ansible.builtin.set_fact:
    django_environment: "{{ django_environment | combine({'DATABASE_PASSWORD': '{{ django_environment_db_password }}'}) }}"
  tags:
    - django.migrate
    - deploy-web
    - deploy-backend
