---

- name: Create the meta data directory
  file: path={{ virtualenv_path }}/meta
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0774
        state=directory
  tags:
    - release

- name: Create repo directory
  file:
    path: "{{ project_path }}"
    state: directory
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    mode: 0755

- name: Check that repo is already setup
  stat:
    path: "{{ project_path }}/.git"
  register: repo_setup

- name: Record previous git info
  shell: git -C {{ project_path }} rev-parse HEAD > {{ virtualenv_path }}/meta/{{ application_name }}.gitsha
  become: true
  become_user: "{{ gunicorn_user }}"
  when: collect_release_info and repo_setup.stat.exists
  tags:
    - release
    - skip_ansible_lint

- name: Record deployment start timestamp
  shell: date -Iseconds > {{ virtualenv_path }}/meta/deployment_start
  when: collect_release_info and repo_setup.stat.exists
  tags:
    - release

- name: Setup the Git repo
  git: repo={{ git_repo }}
       version={{ git_branch }}
       dest={{ project_path }}
       accept_hostkey=yes
       update=yes force=yes
  become: true
  become_user: "{{ gunicorn_user }}"
  tags: git
  notify:
    - Trigger release notification

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ project_path }}"
  tags: git
  changed_when: false
