---

- name: Add Maxmind PPA
  ansible.builtin.apt_repository:
    repo: 'ppa:maxmind/ppa'
    state: present

- name: Install libmaxminddb
  ansible.builtin.apt:
    name:
      - libmaxminddb0
      - libmaxminddb-dev
      - mmdb-bin
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags: packages

- name: Maxmind directory
  ansible.builtin.file:
    path: "{{ django_geoip_path }}"
    mode: 0755
    owner: "{{ gunicorn_user }}"
    state: directory

- name: Add script to update maxmind
  ansible.builtin.template:
    src: update-maxmind.sh.j2
    dest: "{{ django_geoip_path }}/update-maxmind.sh"
    mode: 0755

- name: Update maxmind database
  ansible.builtin.command:
    cmd: "{{ django_geoip_path }}/update-maxmind.sh"
  become_user: "{{ gunicorn_user }}"
  changed_when: false

- name: apt | ensure cron is installed
  ansible.builtin.apt:
    name: cron
    state: present

- name: cron task to update daily
  ansible.builtin.cron:
    name: "maxmind autoupdate"
    minute: 0
    hour: 3
    user: "{{ gunicorn_user }}"
    job: "{{ django_geoip_path }}/update-maxmind.sh > /tmp/update_maxmind.log 2>&1"
