---

- name: Record previous git info
  ansible.builtin.shell: "git -C {{ virtualenv_path }}/src/{{ item.name }} rev-parse HEAD || true > {{ virtualenv_path }}/meta/{{ item.name }}.gitsha"
  with_items: "{{ release_notifications }}"
  when: collect_release_info
  become: true
  become_user: "{{ gunicorn_user }}"
  tags:
    - release_tag
    - skip_ansible_lint
  changed_when: false

- name: Install build dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - cmake
    - pkg-config
    - libcairo2-dev
  tags:
    - djangoreq

- name: Install packages required by the Django app inside virtualenv
  command: "uv pip sync {{ requirements_file }}"
  environment:
    VIRTUAL_ENV: "{{ virtualenv_path }}"
  become: true
  become_user: "{{ gunicorn_user }}"
  notify:
    - Trigger release notification
  tags:
    - djangoreq
