---

- name: Install build dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - cmake
    - pkg-config
    - libcairo2-dev
  tags:
    - djangoreq

- name: Install packages required by the Django app inside virtualenv
  ansible.builtin.command: "uv pip sync {{ requirements_file }}"
  environment:
    VIRTUAL_ENV: "{{ virtualenv_path }}"
  become: true
  become_user: "{{ gunicorn_user }}"
  notify:
    - Trigger release notification
  tags:
    - djangoreq
  changed_when: false
