---

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages

- name: Create the virtualenv
  command: virtualenv -p python3.8 {{ virtualenv_path }}
           creates={{ virtualenv_path }}/bin/activate
  when: ansible_distribution_version == "20.04"

- name: Seet ownership of app directory
  file:
    path: "{{ virtualenv_path }}"
    state: directory
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_user }}"

- name: Create the virtualenv postactivate script to set environment variables
  template: src=virtualenv_postactivate.j2
            dest={{ virtualenv_path }}/bin/postactivate
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0640
            backup=yes
  tags:
    - deploy
    - deploy-backend
    - deploy-web
