---

- name: Install virtualenv
  ansible.builtin.pip:
    name: virtualenv
  tags: packages

- name: Create the virtualenv
  ansible.builtin.command:
    cmd: virtualenv -p {{ virtualenv_python_version }} {{ virtualenv_path }}
    creates: "{{ virtualenv_path }}/bin/activate"

- name: Set ownership of app directory
  ansible.builtin.file:
    path: "{{ virtualenv_path }}"
    state: directory
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_user }}"
    mode: "0755"

- name: Create the virtualenv postactivate script to set environment variables
  ansible.builtin.template:
    src: virtualenv_postactivate.j2
    dest: "{{ virtualenv_path }}/bin/postactivate"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    mode: "0640"
    backup: true
  tags:
    - deploy
    - deploy-backend
    - deploy-web
  notify: restart application
