---

- name: Install build dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - cmake
    - pkg-config
    - libcairo2-dev
  tags:
    - djangoreq

- name: Install packages required by the Django app inside virtualenv
  ansible.builtin.shell:
    cmd: "{{ virtualenv_path }}/bin/python3 -m pip install -U uv && {{ virtualenv_path }}/bin/uv sync --active --no-dev --extra production"
    chdir: "{{ project_path }}"
  environment:
    VIRTUAL_ENV: "{{ virtualenv_path }}"
  become: true
  become_user: "{{ gunicorn_user }}"
  notify:
    - Trigger release notification
  tags:
    - djangoreq
  changed_when: false
