---

git_repo: https://github.com/okfde/fragdenstaat_de.git

ssh_port: 22

maintenance: no
maintenance_media: no
maintenance_admin_ip: no

hostname: "{{ inventory_hostname }}"
project_name: fragdenstaat.de
application_name: fragdenstaat_de
mail_domain: mail.fragdenstaat.de
domain_name: fragdenstaat.de
web_server_name: fragdenstaat.de
web_server_url: "https://{{ web_server_name }}"
media_server_name: media.frag-den-staat.de
media_server_url: "https://{{ media_server_name }}"
static_server_name: static.frag-den-staat.de
static_server_url: "https://{{ static_server_name }}"
static_asset_path: "https://static.frag-den-staat.de/static/js/"

https_domains:
  - ["{{ web_server_name }}", "www.{{ web_server_name }}"]
  - ["{{ media_server_name }}"]
  - ["{{ static_server_name }}"]
  - ["{{ mail_domain }}", "{{ domain_name }}"]
  - ["app.fragdenstaat.de"]
  - ["shop.fragdenstaat.de"]
  - ["blog.fragdenstaat.de"]
  - ["mta-sts.fragdenstaat.de"]
letsencrypt_registration_email: info@fragdenstaat.de
letsencrypt_tmp_dir: /opt/letsencrypt/tmp
letsencrypt_renew_hooks:
  - domain: "{{ web_server_name }}"
    command: systemctl reload nginx
  - domain: "{{ media_server_name }}"
    command: systemctl reload nginx
  - domain: "{{ static_server_name }}"
    command: systemctl reload nginx
  - domain: "{{ mail_domain }}"
    command: "systemctl reload nginx postfix dovecot"

db_host: "127.0.0.1"
db_name: "{{ application_name }}"
db_user: "{{ application_name }}"
db_user_readonly: "{{ application_name }}_readonly"

# Gunicorn settings.
gunicorn_num_workers: 10
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps

onion_service_enabled: no
gunicorn_onion_num_workers: 2
onion_web_server: ""
onion_web_server_url: "http://{{ onion_web_server }}"
onion_media_server: "media."
onion_static_server: "static."
onion_media_server_url: "http://{{ onion_media_server }}"
onion_static_server_url: "http://{{ onion_static_server }}"
onion_static_url: "http://media."
onion_media_url: "http://static."
onion_services: {}

# Temporary here
virtualenv_path: "/var/www/fragdenstaat.de"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "/var/www/fragdenstaat.de/logs"

htpasswd:
  admin:
    - name: user
      password: password

django_media_root: "/var/www/fragdenstaat.de/storage/files"
django_static_root: "/var/www/fragdenstaat.de/public/static"

django_settings_file: "{{ application_name }}.settings.development"
django_configuration: "Dev"

django_geoip_path: "/var/www/fragdenstaat.de/data"
django_secret_url_admin: "admin"
protected_urls:
  - url: "/admin/"
    realm: admin
    only_ip: no

rate_limited_urls:
  - url: /account/login/
    zone: login
    auth: no

release_repo: okfde/fragdenstaat_de
release_notifications:
  - name: django-filingcabinet
    repo: okfde/django-filingcabinet
  - name: froide
    repo: okfde/froide
  - name: froide-campaign
    repo: okfde/froide-campaign
  - name: froide-crowdfunding
    repo: okfde/froide-crowdfunding
  - name: froide-exam
    repo: okfde/froide-exam
  - name: froide-fax
    repo: okfde/froide-fax
  - name: froide-food
    repo: okfde/froide-food
  - name: froide-legalaction
    repo: okfde/froide-legalaction
  - name: froide-payment
    repo: okfde/froide-payment

frontend_modules:
  - package: froide
  - package: froide_food
  - package: froide_payment
  - package: filingcabinet

celery_worker:
  - name: celery
    queues: "celery"
    worker: 3
  - name: mail
    queues: "emailfetch,email"
    worker: 1
  - name: mailsend
    queues: "emailsend"
    worker: 2
  - name: mailsend_bulk
    queues: "emailsend_bulk"
    worker: 4
  - name: search
    queues: "searchindex"
    worker: 4
  - name: celery_solo_1
    queues: "redact,ocr"
    worker: 1
    type: slow
  - name: celery_solo_2
    queues: "redact,ocr,convert,convert_office,document"
    worker: 1
    type: slow
  - name: celery_solo_3
    queues: "redact,document"
    worker: 2
    type: slow

rabbitmq_admin_password: password
rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: password
celery_broker_url: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@localhost/{{ rabbitmq_application_vhost }}"

# This needs tessdata/ for tesseract >= 4 starting Ubuntu 18.04
tesseract_data_path: /usr/share/tesseract-ocr/4.00/tessdata/

dovecot_passwdfile_scheme: 'sha512-crypt'

email_accounts:
  - user: mail@fragdenstaat.de
    password: "password"
  - user: mail@fragdenstaat.de
    password: "password"

email_host: "127.0.0.1"
email_host_user: "mail@fragdenstaat.de"
email_host_password: password
foi_email_host: "127.0.0.1"
foi_email_host_user: "mail@fragdenstaat.de"
foi_email_host_password: password
bounce_email_host: "127.0.0.1"
bounce_email_host_user: "mail@fragdenstaat.de"
bounce_email_host_password: password
unsubscribe_email_host: "127.0.0.1"
unsubscribe_email_host_user: "mail@fragdenstaat.de"
unsubscribe_email_host_password: password


email_alias:
  - from: "test@fragdenstaat.de"
    to: "root@fragdenstaat.de"

alias_foi_domains: []

bad_referrers: []

letsencrypt_enabled: no

# For dovecot and postfix
mail_cert_filename: "/etc/letsencrypt/live/{{ mail_domain }}/fullchain.pem"
mail_privkey_filename: "/etc/letsencrypt/live/{{ mail_domain }}/privkey.pem"

backup_ftp_url: "ftp://user@server"
backup_ftp_password: "password"
backup_gpg_password: "password"

nginx_static_dir: "/var/www/fragdenstaat.de/public/static/"
nginx_media_dir: "/var/www/fragdenstaat.de/storage"
nginx_private_media_path: "/var/www/fragdenstaat.de/storage/"

nginx_public_media:
  - url: "/files/legalaction/"
  - url: "/files/media/"
  - url: "/files/profile/"
  - url: "/files/docs/"
    force_download: true
  - url: "/files/export/"
    force_download: true

nginx_public_privileged_media:
  - "/files/campaign/"

nginx_private_media:
  - url: "/protected"
    dir: "files"
    force_download: true
  - url: "/private_main"
    dir: "private/main"
  - url: "/private_thumbnails"
    dir: "private/thumbnails"
  - url: "/filingcabinet-private"
    dir: "files"

nginx_private_media_prefix:
  - url: "/files/foi/"
  - url: "/files/docs-private/"
  - url: "/smedia"


redirect_domains:
  - from: "blog.fragdenstaat.de"
    domain: "fragdenstaat.de/blog"
    https: true
  - from: "shop.fragdenstaat.de"
    domain: "fragdenstaat.de/shop"
    https: true
  - from: "app.fragdenstaat.de"
    domain: "fragdenstaat.de/app"
    https: true
  - from: "mail.fragdenstaat.de"
    domain: "fragdenstaat.de"
    https: true
  - from: "media.frag-den-staat.de"
    domain: "media.frag-den-staat.de"
    https: false
  - from: "static.frag-den-staat.de"
    domain: "static.frag-den-staat.de"
    https: false

redirect_paths:
  - from: "^/files/foi/30800/"
    path: "/media-30800/"
  - from: "^/de/"
    path: "/"
  - from: "^/r/"
    path: "/a/"

media_legal_paths: []
# - path: "/files/foi/110867/bfr-stellungnahme.pdf"
#   link: "https://fragdenstaat.de/zensurheberrecht"

media_redirect_paths:
  - from: "/files/media/main/2e/bc/2ebc2ed7-51e4-4717-9fc7-a34225bebc5c/sog-masterplan-csu.pdf"
    path: "https://fragdenstaat.de/dokumente/30-sog-masterplan-csu/"
# - from: "/files/foi/110867/bfr-stellungnahme.pdf"
#   path: "https://fragdenstaat.de/dokumente/66/"

# redone in production!
simple_files:
  - path: "/robots.txt"
    filename: robots.txt
  - path: "/.well-known/apple-app-site-association"
    filename: apple-app-site-association
    mimetype: 'application/pkcs7-mime'
  - path: "/.well-known/apple-developer-merchantid-domain-association"
    filename: apple-developer-merchantid-domain-association.dms
  - path: "/BingSiteAuth.xml"
    filename: BingSiteAuth.xml
  - filename: mta-sts.txt

cors_exceptions:
  - url: "/api/v1/campaigninformationobject"
    origins:
      - "__static__"
      - "__media__"
      - "https://okfde.github.io"

# CSP supports __web__, __media__ and __static__ variable__s

content_security_policy:
  "default-src": "'none'"
  "script-src": "'self' 'unsafe-inline' __static__ https://traffic.okfn.de https://js.stripe.com"
  "style-src": "'self' 'unsafe-inline' __static__"
  "img-src": "'self' data: blob: __static__ __media__ https://traffic.okfn.de https://www.betterplace.org https://betterplace-assets.betterplace.org https://i.vimeocdn.com https://raw.githubusercontent.com *.tile.openstreetmap.org *.global.ssl.fastly.net i.ytimg.com"
  "media-src": "__static__ __media__"
  "worker-src": "'self' blob: __static__"
  "frame-src": "'self' blob: __static__ __media__ https://okfde.github.io https://player.vimeo.com https://www.youtube-nocookie.com https://media.ccc.de https://js.stripe.com https://hooks.stripe.com https://www.paypal.com"
  "object-src": "'self' __media__"
  "connect-src": "'self' __static__ __media__ https://api.betterplace.org/ https://sentry.okfn.de https://api.stripe.com"
  "child-src": "'self' blob: __static__"
  "base-uri": "'none'"
  "font-src": "data: __static__"
  "manifest-src": "__static__"
  "form-action": "'self' __web__ https://forum.okfn.de https://www.paypal.com https://pretix.eu https://hooks.stripe.com https://stripe.com https://r.girogate.de"
  "frame-ancestors": "'self'"
  "report-uri": "https://sentry.okfn.de/api/3/security/?sentry_key=f00c20a879414df69051163a90597a8c"

content_security_policy_overrides:
  - url: "~^/account/authorize/"
    directives:
      "form-action": "* fragdenstaat:"
  - url: "~^/kampagnen/lebensmittelkontrolle/app/embed/"
    directives:
      "frame-ancestors": "*"
  - url: "~^/kampagne/.*/embed/$"
    directives:
      "frame-ancestors": "*"
  - url: "~^/klagen/.*$"
    directives:
      "frame-ancestors": "*"
  - url: "~^\\w+-admin/cms/page/edit-plugin/\\d+/"
    directives:
      "frame-src": "*"
  - url: "~^/aktionen/ifg-meisterschaften/.*$"
    directives:
      "frame-src": "'self' https://challonge.com"
  - url: "~^(/en/action|/aktionen)/frontex/.*$"
    directives:
      "frame-src": "'self' https://act.wemove.eu"


static_content_security_policy:
  - "default-src 'self' data: blob: __web__ __media__"
  - "style-src 'self' data: 'unsafe-inline'"
  - "connect-src 'self' __web__ __media__"
  - "frame-ancestors *"
  - "report-uri https://sentry.okfn.de/api/3/security/?sentry_key=f00c20a879414df69051163a90597a8c"

media_content_security_policy:
  - "default-src 'none'"
  - "style-src 'unsafe-inline'"
  - "object-src 'self'"
  - "img-src 'self'"
  - "connect-src 'self'"
  - "media-src 'self'"
  - "frame-ancestors *"
  - "report-uri https://sentry.okfn.de/api/3/security/?sentry_key=f00c20a879414df69051163a90597a8c"

priviliged_media_content_security_policy:
  - "default-src 'self' data: __static__"
  - "script-src 'self' 'unsafe-inline' __static__ https://traffic.okfn.de"
  - "style-src 'self' 'unsafe-inline' __static__"
  - "img-src 'self' data: blob: __static__ https://traffic.okfn.de https://www.betterplace.org https://betterplace-assets.betterplace.org https://i.vimeocdn.com https://raw.githubusercontent.com *.tile.openstreetmap.org *.global.ssl.fastly.net *.yelpcdn.com"
  - "worker-src 'self' blob: __static__"
  - "frame-src 'self' blob: __static__ __web__ https://okfde.github.io https://www.betterplace.org https://player.vimeo.com https://www.youtube-nocookie.com https://media.ccc.de https://challonge.com"
  - "object-src 'self' __web__"
  - "connect-src 'self' __web__"
  - "child-src blob: __static__"
  - "frame-ancestors *"
  - "report-uri https://sentry.okfn.de/api/3/security/?sentry_key=f00c20a879414df69051163a90597a8c"


nginx_extra_domains:
  - domain: mta-sts.fragdenstaat.de
    files:
      - path: "/.well-known/mta-sts.txt"
        filename: mta-sts.txt


# Fill this in

django_sentry_dsn: ""
django_sentry_public_dsn: ""
sentry_auth_token: ""
sentry_url: ""
sentry_org: ""
sentry_project: ""
sentry_webhook_url: ""

yelp_api_key: ""

twilio_account_sid: ""
twilio_auth_token: ""
twilio_from_number: ""

stripe_public_key: ""
stripe_private_key: ""
stripe_webhook_cc_signing_key: ""
stripe_webhook_sepa_signing_key: ""
stripe_webhook_sofort_signing_key: ""

paypal_client_id: ""
paypal_client_secret: ""
paypal_api_url: ""

slack_webhook_url: ""

geoip_license_key: ""