---

git_repo: https://github.com/okfde/fragdenstaat_de.git

hostname: fragdenstaat.de
project_name: fragdenstaat.de
application_name: fragdenstaat_de
mail_hostname: fragdenstaat.de
nginx_server_name: fragdenstaat.de

db_host: "127.0.0.1"
db_name: "{{ application_name }}"
db_user: "{{ application_name }}"

# Gunicorn settings.
gunicorn_num_workers: 3
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps


# Temporary here
virtualenv_path: "/var/www/fragdenstaat.de"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "/var/www/fragdenstaat.de/logs"

nginx_static_dir: "/var/www/fragdenstaat.de/public/static/"
nginx_media_dir: "/var/www/fragdenstaat.de/storage"
nginx_private_media_prefix: "/var/www/fragdenstaat.de/storage"

htpasswd:
  - name: user
    password: password

django_media_root: "/var/www/fragdenstaat.de/storage/files"
django_static_root: "/var/www/fragdenstaat.de/public/static"

django_settings_file: "{{ application_name }}.settings.development"
django_configuration: "Dev"

django_geoip_path: "/var/www/fragdenstaat.de/data"
django_secret_url_admin: "admin"

celery_num_workers: 2
celerymail_num_workers: 1
rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: password
celery_broker_url: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@localhost/{{ rabbitmq_application_vhost }}"

dovecot_passwdfile_scheme: 'sha512-crypt'

email_accounts:
  - user: mail@fragdenstaat.de
    password: "password"
  - user: mail@fragdenstaat.de
    password: "password"

email_host: "127.0.0.1"
email_host_user: "mail@fragdenstaat.de"
email_host_password: password
foi_email_host: "127.0.0.1"
foi_email_host_user: "mail@fragdenstaat.de"
foi_email_host_password: password

email_alias:
  - from: "test@fragdenstaat.de"
    to: "root@fragdenstaat.de"

alias_foi_domains: []


letsencrypt_enabled: no
letsencrypt_dir: "/etc/letsencrypt/live/fragdenstaat.de/"
cert_filename: "/etc/letsencrypt/live/fragdenstaat.de/fullchain.pem"
privkey_filename: "/etc/letsencrypt/live/fragdenstaat.de/privkey.pem"

backup_ftp_url: "ftp://user@server"
backup_ftp_password: "password"
backup_gpg_password: "password"

nginx_public_media:
  - /files/legalaction
  - /files/campaign
  - /files/media
  - /files/profile

nginx_private_media:
  - url: "/protected"
    dir: ""
  - url: "/private_main"
    dir: "private/main"
  - url: "/private_thumbnails"
    dir: "private/thumbnails"


redirect_domains:
  - from: "blog.fragdenstaat.de"
    domain: "fragdenstaat.de/blog"

redirect_paths:
  - from: "/files/foi/30800/"
    path: "/media-30800/"


simple_files:
  - path: "/robots.txt"
    content: "User-agent: *\\nDisallow:\\n"
  - path: "/.well-known/apple-app-site-association"
    content: '{"applinks":{"apps":[],"details":[{"appID":"93C29USLP6.de.okfn.fragdenstaat","paths":["/a/*","/anfrage/*"]}]}}'
    mimetype: 'application/pkcs7-mime'

django_sentry_dsn: ""
content_security_policy:
  - "default-src 'self' data:"
  - "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://traffic.okfn.de"
  - "style-src 'self' 'unsafe-inline'"
  - "img-src 'self' data: blob: https://traffic.okfn.de https://www.betterplace.org https://betterplace-assets.betterplace.org https://i.vimeocdn.comhttps://i.v https://raw.githubusercontent.com *.tile.openstreetmap.org *.global.ssl.fastly.net *.yelpcdn.com"
  - "worker-src 'self'"
  - "frame-src 'self' https://www.betterplace.org https://player.vimeo.com https://media.ccc.de https://challonge.com"
  - "report-uri https://sentry.okfn.de/api/4/csp-report/?sentry_key=b0305966ad35428b88f611c796792749"
