---

git_repo: https://github.com/okfde/fragdenstaat_de.git

ssh_port: 22

maintenance: no
maintenance_media: no
maintenance_admin_ip: no

hostname: "{{ inventory_hostname }}"
project_name: fragdenstaat.de
application_name: fragdenstaat_de
mail_domain: mail.fragdenstaat.de
domain_name: fragdenstaat.de
web_server_name: fragdenstaat.de
media_server_name: media.frag-den-staat.de
static_server_name: static.frag-den-staat.de
static_asset_path: "https://static.frag-den-staat.de/static/js/"

https_domains:
  - ["{{ web_server_name }}", "www.{{ web_server_name }}"]
  - ["{{ media_server_name }}"]
  - ["{{ static_server_name }}"]
  - ["{{ mail_domain }}", "{{ domain_name }}"]
letsencrypt_registration_email: info@fragdenstaat.de
letsencrypt_tmp_dir: /opt/letsencrypt/tmp
letsencrypt_renew_hooks:
  - domain: "{{ web_server_name }}"
    command: systemctl reload nginx
  - domain: "{{ media_server_name }}"
    command: systemctl reload nginx
  - domain: "{{ static_server_name }}"
    command: systemctl reload nginx
  - domain: "{{ mail_domain }}"
    command: "systemctl reload nginx postfix dovecot"

db_host: "127.0.0.1"
db_name: "{{ application_name }}"
db_user: "{{ application_name }}"
db_user_readonly: "{{ application_name }}_readonly"

# Gunicorn settings.
gunicorn_num_workers: 10
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps

# Temporary here
virtualenv_path: "/var/www/fragdenstaat.de"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "/var/www/fragdenstaat.de/logs"

htpasswd:
  admin:
    - name: user
      password: password

django_media_root: "/var/www/fragdenstaat.de/storage/files"
django_static_root: "/var/www/fragdenstaat.de/public/static"

django_settings_file: "{{ application_name }}.settings.development"
django_configuration: "Dev"

django_geoip_path: "/var/www/fragdenstaat.de/data"
django_secret_url_admin: "admin"
protected_urls:
  - url: "/admin/"
    realm: admin

rate_limited_urls:
  - url: /account/login/
    zone: login
    auth: no

release_repo: okfde/fragdenstaat_de
release_notifications:
  - name: froide
    repo: okfde/froide
  - name: froide-campaign
    repo: okfde/froide-campaign
  - name: froide-legalaction
    repo: okfde/froide-legalaction
  - name: froide-crowdfunding
    repo: okfde/froide-crowdfunding
  - name: froide-fax
    repo: okfde/froide-fax
  - name: froide-exam
    repo: okfde/froide-exam
  - name: froide-food
    repo: okfde/froide-food
  - name: froide-payment
    repo: okfde/froide-payment
  - name: django-filingcabinet
    repo: okfde/django-filingcabinet

frontend_modules:
  - package: froide
  - package: froide_food
  - package: froide_payment
  - package: filingcabinet

celery_worker:
  - name: celery
    queues: "celery"
    worker: 3
  - name: mail
    queues: "emailfetch,email"
    worker: 1
  - name: mailsend
    queues: "emailsend"
    worker: 4
  - name: mailsend_bulk
    queues: "emailsend_bulk"
    worker: 1
  - name: search
    queues: "searchindex"
    worker: 4
  - name: celery_solo_1
    queues: "redact,ocr"
    worker: 1
    type: slow
  - name: celery_solo_2
    queues: "redact,ocr,convert,convert_office,document"
    worker: 1
    type: slow
  - name: celery_solo_3
    queues: "redact"
    worker: 1
    type: slow

rabbitmq_admin_password: password
rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: password
celery_broker_url: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@localhost/{{ rabbitmq_application_vhost }}"

# This needs tessdata/ for tesseract >= 4 starting Ubuntu 18.04
tesseract_data_path: /usr/share/tesseract-ocr/4.00/tessdata/

dovecot_passwdfile_scheme: 'sha512-crypt'

email_accounts:
  - user: mail@fragdenstaat.de
    password: "password"
  - user: mail@fragdenstaat.de
    password: "password"

email_host: "127.0.0.1"
email_host_user: "mail@fragdenstaat.de"
email_host_password: password
foi_email_host: "127.0.0.1"
foi_email_host_user: "mail@fragdenstaat.de"
foi_email_host_password: password
bounce_email_host: "127.0.0.1"
bounce_email_host_user: "mail@fragdenstaat.de"
bounce_email_host_password: password

email_alias:
  - from: "test@fragdenstaat.de"
    to: "root@fragdenstaat.de"

alias_foi_domains: []

bad_referrers: []

letsencrypt_enabled: no

# For dovecot and postfix
mail_cert_filename: "/etc/letsencrypt/live/{{ mail_domain }}/fullchain.pem"
mail_privkey_filename: "/etc/letsencrypt/live/{{ mail_domain }}/privkey.pem"

backup_ftp_url: "ftp://user@server"
backup_ftp_password: "password"
backup_gpg_password: "password"

nginx_static_dir: "/var/www/fragdenstaat.de/public/static/"
nginx_media_dir: "/var/www/fragdenstaat.de/storage"
nginx_private_media_path: "/var/www/fragdenstaat.de/storage/"

nginx_public_media:
  - /files/legalaction
  - /files/media
  - /files/profile
  - /files/docs
  - /files/export

nginx_public_privileged_media:
  - "/files/campaign"

nginx_private_media:
  - url: "/protected"
    dir: "files"
    force_download: true
  - url: "/private_main"
    dir: "private/main"
  - url: "/private_thumbnails"
    dir: "private/thumbnails"

nginx_private_media_prefix:
  - url: "/files/foi"
  - url: "/smedia"


redirect_domains:
  - from: "blog.fragdenstaat.de"
    domain: "fragdenstaat.de/blog"
  - from: "mail.fragdenstaat.de"
    domain: "fragdenstaat.de"
  - from: "media.frag-den-staat.de"
    domain: "media.frag-den-staat.de"
  - from: "static.frag-den-staat.de"
    domain: "static.frag-den-staat.de"


redirect_paths:
  - from: "^/files/foi/30800/"
    path: "/media-30800/"
  - from: "^/de/"
    path: "/"

media_legal_paths:
  - path: "/files/foi/110867/bfr-stellungnahme.pdf"
    link: "https://fragdenstaat.de/zensurheberrecht"

media_redirect_paths:
  - from: "/files/media/main/2e/bc/2ebc2ed7-51e4-4717-9fc7-a34225bebc5c/sog-masterplan-csu.pdf"
    path: "https://fragdenstaat.de/dokumente/30-sog-masterplan-csu/"
  - from: "/files/foi/110867/bfr-stellungnahme.pdf"
    path: "https://fragdenstaat.de/dokumente/66/"

simple_files:
  - path: "/robots.txt"
    filename: robots.txt
  - path: "/.well-known/apple-app-site-association"
    filename: apple-app-site-association
    mimetype: 'application/pkcs7-mime'
  - path: "/.well-known/apple-developer-merchantid-domain-association"
    filename: apple-developer-merchantid-domain-association.dms
  - path: "/BingSiteAuth.xml"
    filename: BingSiteAuth.xml
  - path: "/nope"
    filename: bad_referrer.html
    mimetype: 'text/html'

web_cors_for_media:
  - "/api/v1/campaigninformationobject"

content_security_policy:
  "default-src": "'none'"
  "script-src": "'self' 'unsafe-inline' https://static.frag-den-staat.de https://traffic.okfn.de https://js.stripe.com"
  "style-src": "'self' 'unsafe-inline' https://static.frag-den-staat.de"
  "img-src": "'self' data: blob: https://static.frag-den-staat.de https://media.frag-den-staat.de https://traffic.okfn.de https://www.betterplace.org https://betterplace-assets.betterplace.org https://i.vimeocdn.com https://raw.githubusercontent.com *.tile.openstreetmap.org *.global.ssl.fastly.net i.ytimg.com"
  "media-src": "https://static.frag-den-staat.de https://media.frag-den-staat.de"
  "worker-src": "'self' blob: https://static.frag-den-staat.de"
  "frame-src": "'self' blob: https://static.frag-den-staat.de https://media.frag-den-staat.de https://okfde.github.io https://www.betterplace.org https://betterplace-assets.betterplace.org https://player.vimeo.com https://www.youtube-nocookie.com https://media.ccc.de https://challonge.com https://www.foodwatch.org/de/iframe/ https://js.stripe.com https://hooks.stripe.com https://www.paypal.com"
  "object-src": "'self' https://media.frag-den-staat.de"
  "connect-src": "'self' https://static.frag-den-staat.de https://media.frag-den-staat.de https://api.betterplace.org/ https://sentry.okfn.de https://api.stripe.com"
  "child-src": "blob: https://static.frag-den-staat.de"
  "base-uri": "'none'"
  "font-src": "data: https://static.frag-den-staat.de"
  "manifest-src": "https://static.frag-den-staat.de"
  "form-action": "'self' https://fragdenstaat.de https://forum.okfn.de https://www.paypal.com https://pretix.eu https://hooks.stripe.com https://stripe.com https://r.girogate.de"
  "frame-ancestors": "*"
  "report-uri": "https://sentry.okfn.de/api/4/csp-report/?sentry_key=b0305966ad35428b88f611c796792749"

content_security_policy_overrides:
  - url: "~^/account/authorize/"
    directives:
      "form-action": "*"

static_content_security_policy:
  - "default-src 'self' data: blob: https://fragdenstaat.de https://media.frag-den-staat.de"
  - "style-src 'self' data: 'unsafe-inline'"
  - "connect-src 'self' https://fragdenstaat.de https://media.frag-den-staat.de"
  - "frame-ancestors *"
  - "report-uri https://sentry.okfn.de/api/4/csp-report/?sentry_key=b0305966ad35428b88f611c796792749"

media_content_security_policy:
  - "default-src 'none'"
  - "style-src 'unsafe-inline'"
  - "object-src 'self'"
  - "connect-src 'self'"
  - "media-src 'self'"
  - "frame-ancestors *"
  - "report-uri https://sentry.okfn.de/api/4/csp-report/?sentry_key=b0305966ad35428b88f611c796792749"

priviliged_media_content_security_policy:
  - "default-src 'self' data: https://static.frag-den-staat.de"
  - "script-src 'self' 'unsafe-inline' https://static.frag-den-staat.de https://traffic.okfn.de"
  - "style-src 'self' 'unsafe-inline' https://static.frag-den-staat.de"
  - "img-src 'self' data: blob: https://static.frag-den-staat.de https://traffic.okfn.de https://www.betterplace.org https://betterplace-assets.betterplace.org https://i.vimeocdn.com https://raw.githubusercontent.com *.tile.openstreetmap.org *.global.ssl.fastly.net *.yelpcdn.com"
  - "worker-src 'self' blob: https://static.frag-den-staat.de"
  - "frame-src 'self' blob: https://static.frag-den-staat.de https://fragdenstaat.de https://okfde.github.io https://www.betterplace.org https://player.vimeo.com https://www.youtube-nocookie.com https://media.ccc.de https://challonge.com"
  - "object-src 'self' https://fragdenstaat.de"
  - "connect-src 'self' https://fragdenstaat.de"
  - "child-src blob: https://static.frag-den-staat.de"
  - "frame-ancestors *"
  - "report-uri https://sentry.okfn.de/api/4/csp-report/?sentry_key=b0305966ad35428b88f611c796792749"


# Fill this in

django_sentry_dsn: ""
django_sentry_public_dsn: ""

yelp_api_key: ""

twilio_account_sid: ""
twilio_auth_token: ""
twilio_from_number: ""

stripe_public_key: ""
stripe_private_key: ""
stripe_webhook_cc_signing_key: ""
stripe_webhook_sofort_signing_key: ""

paypal_client_id: ""
paypal_client_secret: ""
paypal_api_url: ""
