---

git_repo: https://github.com/okfde/fragdenstaat_de.git

hostname: fragdenstaat.de
project_name: fragdenstaat.de
application_name: fragdenstaat_de
mail_hostname: fragdenstaat.de
web_server_name: fragdenstaat.de
media_server_name: media.frag-den-staat.de
static_server_name: static.frag-den-staat.de

https_domains:
  - "{{ web_server_name }}"
  - "{{ media_server_name }}"
  - "{{ static_server_name }}"

db_host: "127.0.0.1"
db_name: "{{ application_name }}"
db_user: "{{ application_name }}"

# Gunicorn settings.
gunicorn_num_workers: 3
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps

# Temporary here
virtualenv_path: "/var/www/fragdenstaat.de"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "/var/www/fragdenstaat.de/logs"

nginx_static_dir: "/var/www/fragdenstaat.de/public/static/"
nginx_media_dir: "/var/www/fragdenstaat.de/storage"
nginx_private_media_path: "/var/www/fragdenstaat.de/storage"

htpasswd:
  - name: user
    password: password

django_media_root: "/var/www/fragdenstaat.de/storage/files"
django_static_root: "/var/www/fragdenstaat.de/public/static"

django_settings_file: "{{ application_name }}.settings.development"
django_configuration: "Dev"

django_geoip_path: "/var/www/fragdenstaat.de/data"
django_secret_url_admin: "admin"

celery_num_workers: 2
celerymail_num_workers: 1
rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: password
celery_broker_url: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@localhost/{{ rabbitmq_application_vhost }}"

# This needs to add tessdata/ for tesseract > 4 starting Ubuntu 18.04
tesseract_data_path: /usr/share/tesseract-ocr/

dovecot_passwdfile_scheme: 'sha512-crypt'

email_accounts:
  - user: mail@fragdenstaat.de
    password: "password"
  - user: mail@fragdenstaat.de
    password: "password"

email_host: "127.0.0.1"
email_host_user: "mail@fragdenstaat.de"
email_host_password: password
foi_email_host: "127.0.0.1"
foi_email_host_user: "mail@fragdenstaat.de"
foi_email_host_password: password

email_alias:
  - from: "test@fragdenstaat.de"
    to: "root@fragdenstaat.de"

alias_foi_domains: []


letsencrypt_enabled: no

# For dovecto and postfix
cert_filename: "/etc/letsencrypt/live/fragdenstaat.de/fullchain.pem"
privkey_filename: "/etc/letsencrypt/live/fragdenstaat.de/privkey.pem"

backup_ftp_url: "ftp://user@server"
backup_ftp_password: "password"
backup_gpg_password: "password"

nginx_public_media:
  - /files/legalaction
  - /files/media
  - /files/profile
  - /files/docs

nginx_public_privileged_media:
  - "/files/campaign"

nginx_private_media:
  - url: "/protected"
    dir: ""
    force_download: true
  - url: "/private_main"
    dir: "private/main"
  - url: "/private_thumbnails"
    dir: "private/thumbnails"

nginx_private_media_prefix:
  - url: "/files/foi"
  - url: "/smedia"


redirect_domains:
  - from: "blog.fragdenstaat.de"
    domain: "fragdenstaat.de/blog"

redirect_paths:
  - from: "/files/foi/30800/"
    path: "/media-30800/"

media_redirect_paths:
  - from: "/files/media/main/2e/bc/2ebc2ed7-51e4-4717-9fc7-a34225bebc5c/sog-masterplan-csu.pdf"
    path: "https://fragdenstaat.de/dokumente/30-sog-masterplan-csu/"

simple_files:
  - path: "/robots.txt"
    content: "User-agent: *\\nDisallow:\\n"
  - path: "/.well-known/apple-app-site-association"
    content: '{"applinks":{"apps":[],"details":[{"appID":"93C29USLP6.de.okfn.fragdenstaat","paths":["/a/*","/anfrage/*"]}]}}'
    mimetype: 'application/pkcs7-mime'

web_cors_for_media:
  - "/api/v1/campaigninformationobject"

content_security_policy:
  - "default-src 'none'"
  - "script-src 'self' 'unsafe-inline' https://static.frag-den-staat.de https://traffic.okfn.de"
  - "style-src 'self' 'unsafe-inline' https://static.frag-den-staat.de"
  - "img-src 'self' data: blob: https://static.frag-den-staat.de https://media.frag-den-staat.de https://traffic.okfn.de https://www.betterplace.org https://betterplace-assets.betterplace.org https://i.vimeocdn.com https://raw.githubusercontent.com *.tile.openstreetmap.org *.global.ssl.fastly.net *.yelpcdn.com"
  - "worker-src 'self' blob: https://static.frag-den-staat.de"
  - "frame-src 'self' blob: https://static.frag-den-staat.de https://media.frag-den-staat.de https://okfde.github.io https://www.betterplace.org https://player.vimeo.com https://www.youtube-nocookie.com https://media.ccc.de https://challonge.com"
  - "object-src 'self' https://media.frag-den-staat.de"
  - "connect-src 'self' https://static.frag-den-staat.de https://media.frag-den-staat.de"
  - "child-src blob: https://static.frag-den-staat.de"
  - "base-uri 'none'"
  - "font-src data: https://static.frag-den-staat.de"
  - "manifest-src https://static.frag-den-staat.de"
  - "form-action 'self' https://www.paypal.com"
  - "report-uri https://sentry.okfn.de/api/4/csp-report/?sentry_key=b0305966ad35428b88f611c796792749"

static_content_security_policy:
  - "default-src 'self' data: blob: https://fragdenstaat.de https://media.frag-den-staat.de"
  - "style-src 'self' data: 'unsafe-inline'"
  - "connect-src 'self' https://media.frag-den-staat.de"
  - "report-uri https://sentry.okfn.de/api/4/csp-report/?sentry_key=b0305966ad35428b88f611c796792749"

media_content_security_policy:
  - "default-src 'none'"
  - "style-src 'unsafe-inline'"
  - "object-src 'self'"
  - "connect-src 'self'"
  - "report-uri https://sentry.okfn.de/api/4/csp-report/?sentry_key=b0305966ad35428b88f611c796792749"

priviliged_media_content_security_policy:
  - "default-src 'self' data: https://static.frag-den-staat.de"
  - "script-src 'self' 'unsafe-inline' https://static.frag-den-staat.de https://traffic.okfn.de"
  - "style-src 'self' 'unsafe-inline' https://static.frag-den-staat.de"
  - "img-src 'self' data: blob: https://static.frag-den-staat.de https://traffic.okfn.de https://www.betterplace.org https://betterplace-assets.betterplace.org https://i.vimeocdn.com https://raw.githubusercontent.com *.tile.openstreetmap.org *.global.ssl.fastly.net *.yelpcdn.com"
  - "worker-src 'self' blob: https://static.frag-den-staat.de"
  - "frame-src 'self' blob: https://static.frag-den-staat.de https://fragdenstaat.de https://okfde.github.io https://www.betterplace.org https://player.vimeo.com https://www.youtube-nocookie.com https://media.ccc.de https://challonge.com"
  - "object-src 'self' https://fragdenstaat.de"
  - "connect-src 'self' https://fragdenstaat.de"
  - "child-src blob: https://static.frag-den-staat.de"
  - "report-uri https://sentry.okfn.de/api/4/csp-report/?sentry_key=b0305966ad35428b88f611c796792749"


# Fill this in

django_sentry_dsn: ""

yelp_api_key: ""

twilio_account_sid: ""
twilio_auth_token: ""
twilio_from_number: ""
