---

- import_tasks: install.yml

- import_tasks: setup_db.yml
  when: inventory_hostname in groups['db']

- import_tasks: setup_replication.yml
  when: groups.get('dbreplica') and inventory_hostname in groups['db']

- import_tasks: setup_replicas.yml
  when: inventory_hostname in groups.get('dbreplica', [])
