---

- name: Setup primary conn info and slot name
  lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} = {{ item.value }}"
    state: present
  loop:
    - { key: "primary_conninfo", value: "'user={{ db_user_replication }} port=5432 host={{ hostvars[groups['db'][0]].host_data.site_ipv4 }} application_name={{ inventory_hostname }}.repl'" }
    - { key: "primary_slot_name", value: "'{{ inventory_hostname.replace('.', '_') }}'" }
  notify:
    - restart postgresql
