- name: Download check_mk agent
  get_url:
    url: "{{ cmk_site_url }}/check_mk/agents/check-mk-agent_{{ cmk_version }}-1_all.deb"
    dest: "/tmp"

- name: Make sure python3 is installed
  become: true
  apt:
    pkg: python3
    state: present

- name: Install check_mk agent
  become: true
  apt:
      deb: "/tmp/check-mk-agent_{{ cmk_version }}-1_all.deb"
      state: present

- include_tasks: install_plugin.yml
  loop:
    - "{{ cmk_host_plugins }}"
  loop_control:
    loop_var: cmk_plugins

- name: "Disable Ubuntu advertisement interfering with apt output parsing"
  command: mv /etc/apt/apt.conf.d/20apt-esm-hook.conf /etc/apt/apt.conf.d/20apt-esm-hook.conf.disabled
  args:
    removes: /etc/apt/apt.conf.d/20apt-esm-hook.conf
    creates: /etc/apt/apt.conf.d/20apt-esm-hook.conf.disabled

- include_tasks: install_plugin.yml
  loop: "{{ group_names | map('extract', cmk_group_plugins) | list | select('defined') }}"
  loop_control:
    loop_var: cmk_plugins

- name: xinetd service activation
  block:
    - name: Install xinetd package
      package:
        name: xinetd
        state: present

    - name: Limit check_mk xinetd service
      lineinfile:
        path: /etc/xinetd.d/check_mk
        insertafter: "#only_from"
        regexp: '^only_from'
        line: "only_from      = 127.0.0.1 {{ cmk_server_ip }}"

    - name: Start and enable xinetd
      service:
        name: xinetd
        state: started
        enabled: true

    - name: Allow check_mk.socket (ufw)
      community.general.ufw:
        rule: allow
        port: 6556
        proto: tcp
        from_ip: "{{ cmk_server_ip }}"