---

- name: restart postgresql
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: reload postgresql config
  become_user: postgres
  community.postgresql.postgresql_query:
    query: SELECT pg_reload_conf()
