- name: Download minio package
  ansible.builtin.get_url:
    url: "https://dl.min.io/server/minio/release/linux-amd64/minio_{{ minio_release }}.deb"
    dest: "/opt/minio_{{ minio_release }}.deb"
    mode: "0440"
  failed_when: "'FAILED' in command_result.stderr"

- name: Download mcli package
  ansible.builtin.get_url:
    url: "https://dl.min.io/client/mc/release/linux-amd64/mcli_{{ mcli_release }}.deb"
    dest: "/opt/mcli_{{ mcli_release }}.deb"
    mode: "0440"
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"

- name: Install minio
  ansible.builtin.apt:
    deb: "/opt/minio_{{ minio_release }}.deb"
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"

- name: Install mcli
  ansible.builtin.apt:
    deb: "/opt/mcli_{{ mcli_release }}.deb"
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"

- name: Install supervisor
  ansible.builtin.apt:
    pkg: supervisor

- name: Create minio supervisor config
  ansible.builtin.template:
    src: minio.conf.j2
    dest: /etc/supervisor/conf.d/minio.conf
    mode: "0600"
    owner: root
    group: root

- name: Re-read the Supervisor config files
  community.general.supervisorctl:
    name: "minio"
    state: present

- name: Configure nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/minio.conf
    mode: "0640"
    owner: root
    group: root
  notify: Reload nginx
