- name: Download minio package
  ansible.builtin.get_url:
    url: "https://dl.min.io/server/minio/release/linux-amd64/minio.deb"
    dest: "/opt/"
    mode: "0440"

- name: Download mcli package
  ansible.builtin.get_url:
    url: "https://dl.min.io/client/mc/release/linux-amd64/mc.deb"
    dest: "/opt/"
    mode: "0440"

- name: Install minio
  ansible.builtin.apt:
    deb: "/opt/minio.deb"

- name: Install mcli
  ansible.builtin.apt:
    deb: "/opt/mc.deb"

- name: Install supervisor
  ansible.builtin.apt:
    pkg: supervisor

- name: Create minio supervisor config
  ansible.builtin.template:
    src: minio.conf.j2
    dest: /etc/supervisor/conf.d/minio.conf
    mode: "0600"
    owner: root
    group: root

- name: Re-read the Supervisor config files
  community.general.supervisorctl:
    name: "minio"
    state: present

- name: Configure nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/minio.conf
    mode: "0640"
    owner: root
    group: root
  notify: Reload nginx
