---

- name: Install additional packages
  apt:
    name:
      - gettext
      - imagemagick
      - tesseract-ocr
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-deu
      - qpdf
      - ocrmypdf
      - optipng
      - jpegoptim
    update_cache: "{{ update_apt_cache }}"
    force: yes
    state: present


- name: Comment out ImageMagick policy entries for PDF none
  replace:
    path: /etc/ImageMagick-6/policy.xml
    regexp: '^(  <policy domain="coder" rights="none" pattern="PDF" />)$'
    replace: '<!-- \1 -->'

- name: Increase ImageMagick cache disk resources
  replace:
    path: /etc/ImageMagick-6/policy.xml
    regexp: '<policy domain="resource" name="disk" value="1GiB"/>'
    replace: '<policy domain="resource" name="disk" value="8GiB"/>'

- name: Add ImageMagick policy entries tmp resource and PDF read/write
  blockinfile:
    path: /etc/ImageMagick-6/policy.xml
    insertbefore: '</policymap>'
    block: |
      <policy domain="coder" rights="read | write" pattern="PDF" />
      <policy domain="resource" name="temporary-path" value="/tmp"/>
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"

- name: Add ImageMagick policy entries for paths
  blockinfile:
    path: /etc/ImageMagick-6/policy.xml
    insertbefore: '</policymap>'
    block: |
      <policy domain="path" rights="read | write" pattern="{{ item }}/*" />
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{ item }} -->"
  with_items:
    - "{{ django_media_root }}/foi"
    - "{{ django_media_root }}/docs"

- replace:
    path: /etc/ImageMagick-6/policy.xml
    regexp: '<policy domain="coder" rights="none" pattern="PDF" />'
    replace: ''
    after: 'Start after line.*'
    backup: yes

- name: Add LibreOffice repository
  apt_repository: repo="ppa:libreoffice/libreoffice-5-3" state=present
  when: ansible_distribution_version == "16.04"

- name: Add LibreOffice repository
  apt_repository: repo="ppa:libreoffice/libreoffice-6-0" state=present
  when: ansible_distribution_version == "18.04"

- name: Install LibreOffice
  apt: name=libreoffice state=latest update_cache=yes
