- name: Install poppler build dependencies
  apt:
    name:
      - checkinstall
      - libfreetype6-dev
      - libfontconfig-dev
      - libnss3-dev
      - libjpeg-dev
      - libtiff-dev
    update_cache: "{{ update_apt_cache }}"
    force: yes
    state: present

- name: Setup poppler build script
  template: src=install_poppler.sh.j2 dest={{ virtualenv_path }}/install_poppler.sh mode=0755

- name: Build and install poppler-utils
  command:  "{{ virtualenv_path }}/install_poppler.sh"
  args:
    creates: "/usr/local/lib/libpoppler.so"
  become: true
