---

- import_tasks: install_additional_packages.yml
  tags: packages

- import_tasks: install_latest_poppler.yml
  tags:
    - packages
    - poppler

- import_tasks: install_latest_imagemagick.yml
  tags:
    - packages

- import_tasks: create_users_and_groups.yml

- import_tasks: set_file_permissions.yml

- import_tasks: setup_virtualenv.yml
  tags: virtualenv

- import_tasks: setup_git_repo.yml
  tags:
    - deploy
    - deploy-backend
    - deploy-web
    - deploy-frontend

- import_tasks: set_file_permissions.yml

- import_tasks: setup_django_app.yml
  tags:
    - deploy
    - deploy-frontend
    - deploy-web
    - deploy-backend

- import_tasks: setup_geoip.yml

- import_tasks: setup_supervisor.yml
  tags: supervisor

- import_tasks: build_frontend.yml

- import_tasks: run_django_tasks.yml
  tags:
    - deploy
    - deploy-backend
    - deploy-web
    - deploy-frontend

- import_tasks: setup_onion_service.yml
  when: onion_service_enabled
  tags:
    - onion

- name: release notifications
  import_tasks: release_notification.yml

- name: restart application
  supervisorctl:
    name: "{{ item }}"
    state: restarted
  with_items:
    - "{{ application_name }}_gunicorn"
    - "{{ application_name }}_uvicorn"
  notify:
    - restart memcached

- name: Reload application
  shell: "supervisorctl pid {{ item }} | xargs kill -s HUP"
  notify:
    - restart memcached
  with_items:
    - "{{ application_name }}_gunicorn"
    - "{{ application_name }}_uvicorn"
  tags:
    - deploy
    - deploy-backend
    - deploy-frontend
    - deploy-web

- name: Reload Onion application
  shell: "supervisorctl pid {{ item }} | xargs kill -s HUP"
  when: onion_service_enabled
  with_items:
    - "{{ application_name }}_gunicorn_onion"
    - "{{ application_name }}_uvicorn_onion"
  notify:
    - restart memcached
  tags:
    - deploy
    - deploy-backend
    - deploy-frontend
    - deploy-web

- import_tasks: setup_cron_tasks.yml
  tags: maintenance
