---

- import_tasks: install_additional_packages.yml
  tags: packages

- import_tasks: create_users_and_groups.yml

- import_tasks: set_file_permissions.yml
  tags:
    - deploy
    - deploy-backend

- import_tasks: setup_virtualenv.yml
  tags: virtualenv

- import_tasks: setup_git_repo.yml
  tags:
    - deploy
    - deploy-backend
    - deploy-frontend

- import_tasks: set_file_permissions.yml
  tags:
    - deploy
    - deploy-backend
    - deploy-frontend

- import_tasks: setup_django_app.yml
  tags:
    - deploy
    - deploy-frontend
    - deploy-backend

- import_tasks: setup_geoip.yml

- import_tasks: setup_supervisor.yml
  tags: supervisor

- import_tasks: build_frontend.yml

- import_tasks: run_django_tasks.yml
  tags:
    - deploy
    - deploy-backend

- name: restart application
  supervisorctl: name={{ application_name }} state=restarted
  notify:
    - restart memcached

- name: Reload application
  shell: "supervisorctl pid {{ application_name }} | xargs kill -s HUP"
  tags:
    - deploy
    - deploy-backend
    - deploy-frontend

- import_tasks: setup_cron_tasks.yml
  tags: maintenance
