---

- name: Install NFS client
  apt:
    name:
      - nfs-common
    update_cache: "{{ update_apt_cache }}"
    force: true
    state: present

- name: Write systemd mount for NFS media
  template:
    src: systemd_mount_media.j2
    dest: "/etc/systemd/system/{{ external_media_storage_unitname }}.mount"

- name: Start NFS media mount
  ansible.builtin.systemd:
    name: "{{ external_media_storage_unitname }}.mount"
    state: started
