---

- name: Ensure that the application file permissions are set properly
  file: path={{ virtualenv_path }}/{{ item }}
        recurse=yes
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        state=directory
  with_items:
    - bin
    - fragdenstaat.de
    - include
    - data
    - lib
    - scripts
    - share
    - src
    - run
    - meta

- name: Creates storage directory
  file:
    path: "{{ virtualenv_path }}/storage"
    state: directory
    owner: "{{ gunicorn_user }}"

- name: Ensure that the storage directory permissions are set properly
  # leading 2 on mode sets group id (setgid), so other files will get group www-data
  command: "find {{ virtualenv_path }}/storage -type d -exec chmod 2750 {} \\;"

- name: Ensure that the storage directory owners are set properly
  command: "find {{ virtualenv_path }}/storage -type d -exec chown {{ gunicorn_user }} {} \\;"

- name: Ensure that the storage directory groups are set properly
  command: "find {{ virtualenv_path }}/storage -type d -exec chgrp www-data {} \\;"
