---

- name: Install Supervisor
  apt: name=supervisor update_cache={{ update_apt_cache }} state=present
  tags:
    - celery

- name: Ensure supervisor service is started
  service: name=supervisor state=started enabled=yes
  tags:
    - celery

- name: Create the Supervisor config file
  template:
    src: "supervisor_{{ item }}.j2"
    dest: "/etc/supervisor/conf.d/{{ item }}.conf"
    backup: yes
  with_items:
    - "app_gunicorn"
    - "app_uvicorn"

- name: Re-read the Supervisor config files
  supervisorctl:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ application_name }}_gunicorn"
    - "{{ application_name }}_uvicorn"

