---

- name: Create the meta data directory
  file: path={{ virtualenv_path }}/meta
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0774
        state=directory
  tags:
    - release

- name: Record previous git info
  shell: git -C {{ project_path }} rev-parse HEAD > {{ virtualenv_path }}/meta/{{ application_name }}.gitsha
  tags:
    - release

- name: Setup the Git repo
  git: repo={{ git_repo }}
       version={{ git_branch }}
       dest={{ project_path }}
       accept_hostkey=yes
       update=yes force=yes
  become: true
  become_user: "{{ gunicorn_user }}"
  when: setup_git_repo is defined and setup_git_repo
  tags: git

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ project_path }}"
  tags: git
