- name: Install msmtp and dependencies
  ansible.builtin.apt:
    pkg: "{{ item }}"
  with_items:
    - msmtp-mta
    - bsd-mailx

- name: Configure msmtp
  ansible.builtin.template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    mode: "0644"

- name: Create /etc/mail.rc
  ansible.builtin.copy:
    src: mail.rc
    dest: /etc/mail.rc
    mode: "0644"

- name: Set crontabs MAILTO var
  community.general.cronvar:
    name: MAILTO
    value: "{{ cron_mailto_from }}"
    user: root
