---

- name: Install JRE
  apt:
    name: default-jre
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags: packages

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  tags: packages

- name: Add Elasticsearch repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main'
    state: present
    update_cache: true
  tags: packages

- name: Install Elasticsearch.
  package:
    name: elasticsearch
    state: present
  tags: packages

- name: Apply heapsize start tuning for systems with greater than 64G memory
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xms'
    line: "-Xms{{ elasticsearch_heapsize }}"
  notify: restart elasticsearch

- name: Apply heapsize start tuning for systems with greater than 64G memory
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xmx'
    line: "-Xmx{{ elasticsearch_heapsize }}"
  notify: restart elasticsearch

- name: Get dictionary file
  get_url:
    url: "https://raw.githubusercontent.com/uschindler/german-decompounder/6227be052f4215294b5a5d498cdcdadfcf7196e6/dictionary-dee.txt"
    dest: "/etc/elasticsearch/analysis/de_DR.xml"
    owner: root
    group: elasticsearch
    mode: 0640

- name: Get hyphenation file
  get_url:
    url: "https://raw.githubusercontent.com/uschindler/german-decompounder/6227be052f4215294b5a5d498cdcdadfcf7196e6/de_DR.xml"
    dest: "/etc/elasticsearch/analysis/de_DR.xml"
    owner: root
    group: elasticsearch
    mode: 0640

- name: Ensure elasticsearch service is running
  service:
    name: elasticsearch
    state: started
    enabled: yes
