---
- name: Trigger release notification
  ansible.builtin.command: "{{ virtualenv_path }}/notify-release.sh"
  become: true
  become_user: "{{ gunicorn_user }}"
  tags:
    - deploy
    - deploy-frontend
    - deploy-web
    - deploy-backend
    - skip_ansible_lint
  ignore_errors: true

- name: restart application
  community.general.supervisorctl:
    name: all
    state: restarted
  notify:
    - restart memcached

- name: restart memcached
  ansible.builtin.service:
    name: memcached
    state: restarted
  changed_when: false
