---

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    pkg:
      - "docker-ce"
    update_cache: true
  retries: 3
  delay: 10

- name: Update apt and install docker-ce-cli
  ansible.builtin.apt:
    pkg:
      - "docker-ce-cli"
      - "containerd.io"
      - "docker-compose-plugin"
      - "apparmor-utils"
    state: latest
    update_cache: true
  retries: 3
  delay: 10
