---
host_data:
  region: unknown
  datacenter: unknown
  interface_name: enp1s0
  mac: 52:54:00:ad:f4:89
  global_ipv4: 192.168.122.123
  global_ipv6: none
  site_ipv4: 192.168.122.123

https_domains:
  - ["test.zerschlagdenstaat.de"]
  - ["static.test.zerschlagdenstaat.de"]
  - ["mail.test.zerschlagdenstaat.de"]
  - ["app.test.zerschlagdenstaat.de"]
  - ["shop.test.zerschlagdenstaat.de"]
  - ["blog.test.zerschlagdenstaat.de"]
  - ["mta-sts.test.zerschlagdenstaat.de"]
