---
host_data:
  region: falkenstein1
  datacenter: fsn1-dc14
  interface_name: enp0s31f6
  mac: 90:1b:0e:ab:a5:66
  global_ipv4: 144.76.157.203
  global_ipv6: 2a01:4f8:231:1ec6::2
  site_ipv4: 192.168.100.5
  disk_type: ssd
  vpn_peer_id: 230

prometheus: true
graylog: true
grafana: true

prometheus_exporter:
  - node_exporter

https_domains:
  - ['mon.zerschlagdenstaat.de']
  - ['log.zerschlagdenstaat.de']

monitor_server_name: 'mon.zerschlagdenstaat.de'
logserver_server_name: 'log.zerschlagdenstaat.de'

borg:
  snapshots:
    - name: monitor
      dev: /dev/vg1/monitor
      mnt: /mnt/monitor-snapshot
  locations: /mnt/monitor-snapshot/graylog/mongodb_data/
  keepdaily: 14
