---
host_data:
  region: falkenstein1
  datacenter: fsn1-dc16
  interface_name: enp41s0
  mac: d0:50:99:f8:ec:47
  global_ipv4: 157.90.130.85
  global_ipv6: 2a01:4f8:252:43e8::2
  site_ipv4: 192.168.100.3
  disk_type: ssd

create_swap_file: false
elasticsearch_heapsize: 22g

https_domains:
  - ["api.farmsubsidy.org"]

prometheus_exporter:
  - node_exporter

icinga:
  vars:
    - ssh_port = 2228
