---
host_data:
  region: falkenstein1
  datacenter: fsn1-dc14
  interface_name: enp0s31f6
  mac: 90:1b:0e:ab:a5:66
  global_ipv4: 144.76.157.203
  global_ipv6: 2a01:4f8:231:1ec6::2
  site_ipv4: 192.168.100.5
  disk_type: ssd
  vpn_peer_id: 230
  wg_publickey: "+IWh/zC8u0SwU80/7+MdQQasNqyPVc1R3FAwLT4KwB4="

prometheus: true
graylog: true
grafana: true

prometheus_exporter:
  - node_exporter

https_domains:
  - ['mon.zerschlagdenstaat.de']
  - ['log.zerschlagdenstaat.de']
  - ['sentry.okfn.de']

monitor_server_name: 'mon.zerschlagdenstaat.de'
logserver_server_name: 'log.zerschlagdenstaat.de'

borg:
  snapshots:
    - name: monitor
      dev: /dev/vg1/monitor
      mnt: /mnt/monitor-snapshot
      lvm_free: 25%
    - name: root
      dev: /dev/vg0/root
      mnt: /mnt/root-snapshot
      lvm_free: 75%
  locations: /mnt/monitor-snapshot/graylog/mongodb_data/ /mnt/root-snapshot/var/lib/docker/volumes/sentry*
  keepdaily: 14

postfix_myorigin: fds-mon.zerschlagdenstaat.de

docker_updates:
  - name: monitor
    cmd: docker compose pull
    dir: /var/www/monitor
    restart: docker compose up -d

scripts:
  - src: cmk_ack.sh
    dest: /usr/local/bin/
    dirmode: "0775"
    owner: root
    group: root
    mode: "0755"
    target: fds-mon.okfn.de
  - src: cmk.sh
    dest: /usr/local/bin/
    dirmode: "0775"
    owner: root
    group: root
    mode: "0755"
    target: fds-mon.okfn.de
  - src: cmk_status.sh
    dest: /usr/local/bin/
    dirmode: "0775"
    owner: root
    group: root
    mode: "0755"
    target: fds-mon.okfn.de
    cron:
      minute: "*"
      hour: "*"
      day: "*"
      month: "*"
      dow: "*"
      job: "/usr/local/bin/cmk_status.sh -q > /dev/null 2>&1"

icinga:
  master: true
  vars:
    - ssh_port = 2228
    - procs_warning = 750
    - procs_critical = 1000
    - swap_wfree = "10%"
    - swap_cfree = "5%"

    - http_vhosts["fragdenstaat.de"] = { http_uri = "https://fragdenstaat.de" }
    - http_vhosts["forum.okfn.de"] = { http_uri = "https://forum.okfn.de" }
    - http_vhosts["metabase.frag-den-staat.de"] = { http_uri = "https://metabase.frag-den-staat.de" }
    - http_vhosts["ogimage.frag-den-staat.de"] = { http_uri = "https://ogimage.frag-den-staat.de" }
    - http_vhosts["ogimage-next.frag-den-staat.de"] = { http_uri = "https://ogimage-next.frag-den-staat.de" }
    - http_vhosts["sentry.okfn.de"] = { http_uri = "https://sentry.okfn.de" }
    - http_vhosts["weblate.frag-den-staat.de"] = { http_uri = "https://weblate.frag-den-staat.de" }

    - disks["vg1-monitor"] = { disk_partitions = "/dev/mapper/vg1-monitor" }
    - node_exporter = 1
    - mailq_warning = 100
    - mailq_critical = 200
    - docker = 1
    - mysql_socket = "/var/run/mysqld/mysqld.sock"
    - smtp_host = "localhost"
    - grafana = 1
    - graylog = 1
    - prometheus = 1
    - graylog_filebeat_bind = "192.168.100.5"
    - graylog_gelf_http_bind = "192.168.100.5"
    - backup = "borg"
