---
host_data:
  region: unknown
  datacenter: unknown
  interface_name: enp1s0
  mac: 52:54:00:23:19:6c
  global_ipv4: 192.168.122.150
  global_ipv6: none
  site_ipv4: 192.168.122.150
  ubuntu: noble

monitor_server: fds-tst.okfn.de
prometheus_exporter:
  - node_exporter

icinga:
  vars:
    - ssh_port = 2228
