---
host_data:
  region: falkenstein1
  datacenter: fsn1-dc14
  interface_name: enp0s31f6
  mac: 90:1b:0e:ab:a5:66
  global_ipv4: 144.76.157.203
  global_ipv6: 2a01:4f8:231:1ec6::2
  site_ipv4: 192.168.100.5
  disk_type: ssd
  vpn_peer_id: 230
  wg_publickey: "+IWh/zC8u0SwU80/7+MdQQasNqyPVc1R3FAwLT4KwB4="
  ubuntu: noble

prometheus: true
graylog: true
grafana: true

prometheus_exporter:
  - node_exporter

https_domains:
  - ['mon.zerschlagdenstaat.de']
  - ['log.zerschlagdenstaat.de']
  - ['sentry.okfn.de']

monitor_server_name: 'mon.zerschlagdenstaat.de'
logserver_server_name: 'log.zerschlagdenstaat.de'

borg:
  snapshots:
    - name: container
      dev: /dev/vg1/container
      mnt: /mnt/container-snapshot
      lvm_free: 25%
    - name: monitor
      dev: /dev/vg1/monitor
      mnt: /mnt/monitor-snapshot
      lvm_free: 25%
    - name: root
      dev: /dev/vg0/root
      mnt: /mnt/root-snapshot
      lvm_free: 50%
  locations: /mnt/monitor-snapshot/ /mnt/container-snapshot/volumes/sentry* -e /mnt/monitor-snapshot/graylog/mongodb_data/ -e /mnt/monitor-snapshot/prometheus/data/data/
  keepdaily: 7

postfix_myorigin: fds-mon.zerschlagdenstaat.de

docker_updates:
  - name: monitor
    cmd: docker compose pull
    dir: /var/www/monitor
    restart: docker compose up -d

icinga:
  master: true
  vars:
    - ssh_port = 2228
    - procs_warning = 750
    - procs_critical = 1000
    - swap_wfree = "5%"
    - swap_cfree = "0%"

    - http_vhosts["fragdenstaat.de"] = { http_uri = "https://fragdenstaat.de" }
    - http_vhosts["forum.okfn.de"] = { http_uri = "https://forum.okfn.de" }
    - http_vhosts["metabase.frag-den-staat.de"] = { http_uri = "https://metabase.frag-den-staat.de" }
    - http_vhosts["ogimage.frag-den-staat.de"] = { http_uri = "https://ogimage.frag-den-staat.de" }
    - http_vhosts["ogimage-next.frag-den-staat.de"] = { http_uri = "https://ogimage-next.frag-den-staat.de" }
    - http_vhosts["sentry.okfn.de"] = { http_uri = "https://sentry.okfn.de" }
    - http_vhosts["weblate.frag-den-staat.de"] = { http_uri = "https://weblate.frag-den-staat.de" }
    - http_vhosts["traffic.okfn.de"] = { http_uri = "https://traffic.okfn.de" }

    - disks["disk vg1-monitor"] = { disk_partitions = "/dev/mapper/vg1-monitor" }
    - disks["disk vg1-container"] = { disk_partitions = "/dev/mapper/vg1-container" }
    - node_exporter = 1
    - mailq_warning = 100
    - mailq_critical = 200
    - docker = 1
    - mysql_socket = "/var/run/mysqld/mysqld.sock"
    - smtp_host = "localhost"
    - grafana = 1
    - graylog = 1
    - prometheus = 1
    - graylog_filebeat_bind = "192.168.100.5"
    - graylog_gelf_http_bind = "192.168.100.5"
    - backup = "borg"
    - elasticsearch = 1
    - smartmon = "sd"

    - tor_proxy = 1
    - tor_proxy_host = "127.0.0.1"
    - tor_proxy_port = 9050
    - tor_onion_target["tor - onion_whistleblow_portal"] = { onion = "cejukxlcaj4umxbtwj3xknyrgr5utkigwvfnymcyvfmh3wlhkec257ad" }
    - tor_onion_target["tor - onion_web_server"] = { onion = "fdstaat23zv6kdmntgkvdzkr7hipl5oqswwi3xawzkj2w2gwsbxmrwyd" }
    - tor_onion_target["tor - onion_media_server"] = { onion = "media.fdscdncc46svip3qd3vtyrrw7435sdftp4wd3crarr3m6iwenitoryad" }
    - tor_onion_target["tor - onion_static_server"] = { onion = "static.fdscdncc46svip3qd3vtyrrw7435sdftp4wd3crarr3m6iwenitoryad" }

    - graylog_api_url = "http://localhost:9010/api/cluster/"
    - graylog_api_token = "{{ icinga_graylog_api_token }}"

dockerupdate:
  graylog:
    path: "/var/www/monitor/"
dockerupdate_compose_lines:
  graylog:
    path: "/var/www/monitor/"
    regexp: "-graylog/graylog:(.*)"
    line: "    image: \"${GRAYLOG_IMAGE:-graylog/graylog:{{ graylog_version }}}\""

graylog_version: "6.3.3"
