---
host_data:
  region: unknown
  datacenter: unknown
  interface_name: enp5s0
  mac: c8:7f:54:70:5b:13
  global_ipv4: 144.76.157.203
  global_ipv6: none
  site_ipv4: 192.168.122.1
  vpn_peer_id: 210

monitor_server: fds-tst.okfn.de
prometheus: false
grafana: false
graylog: false
prometheus_exporter:
  - node_exporter

https_domains:
  - ['test.zerschlagdenstaat.de', '*.test.zerschlagdenstaat.de']
