---
host_data:
  region: falkenstein1
  datacenter: fsn1-dc1
  interface_name: enp0s31f6
  mac: 7c:10:c9:21:fc:db
  global_ipv4: 88.99.57.224
  global_ipv6: 2a01:4f8:10a:a1f::2
  site_ipv4: 192.168.100.4
  disk_type: hdd
  wg_publickey: "n77Y3S6AkvoTUztuSlr8H9UzkkDs2RzhrhQaHJUPLVY="
  vpn_peer_id: 201
  ubuntu: noble

prometheus_exporter:
  - node_exporter

borg:
  locations: /var/www/ /opt/discourse_docker/shared/standalone/backups/default/
  keepdaily: 7
  prescripts_docker:
    - name: metabase
      container_name: postgres
      path: "/var/www/metabase/"
      src: create_postgres_backup_docker.sh
      dest: metabase_backup.sh
      db_name: metabase
      db_user: metabase_user
      db_password: metabase
    - name: nocodb
      container_name: root_db
      path: "/var/www/nocodb/"
      src: create_postgres_backup_docker.sh
      dest: nocodb_backup.sh
      db_name: "{{ nc_db_name }}"
      db_user: "{{ nc_db_user }}"
      db_password: "{{ nc_db_password }}"

icinga:
  vars:
    - ssh_port = 2228
    - backup = "borg"
    - procs_warning = 600
    - procs_critical = 700
    - node_exporter = 1
    - docker = 1
    - ogimage_port = 3000
    - metabase_port = 8042
    - weblate_port = 8020
    - discourse_port = 8035
    - roundcube_port = 9800
    - smartmon = "sd"
    - zammad = 1
