---
host_data:
  region: unknown
  datacenter: unknown
  interface_name: enp1s0
  mac: 52:54:00:ba:72:c8
  global_ipv4: 192.168.122.240
  global_ipv6: none
  site_ipv4: 192.168.122.240

https_domains:
  - ["media.test.zerschlagdenstaat.de"]
