---
host_data:
  region: unknown
  datacenter: unknown
  interface_name: enp1s0
  mac: 52:54:00:ba:72:c8
  global_ipv4: 192.168.122.240
  global_ipv6: none
  site_ipv4: 192.168.122.240

https_domains:
  - ["media.test.zerschlagdenstaat.de"]

monitor_server: fds-tst.okfn.de
prometheus_exporter:
  - node_exporter

nfs_exports:
  - "{{ external_media_storage_src }} 192.168.122.123(rw,sync,no_subtree_check,all_squash,anonuid=1001,anongid=33)"
nfs_allow_from: 192.168.122.123

nginx_media_dir: "/home/storage-box/home"
nginx_private_media_path: "/home/storage-box/home/"
nginx_static_html_dir: "/var/www/static"
