---

- name: restart fdsbot
  ansible.builtin.service:
    name: fdsbot
    state: restarted

- name: reload light cluster postgresql config
  community.postgresql.postgresql_query:
    port: "{{ fdsbot_db_light_port }}"
    query: SELECT pg_reload_conf()
  become_user: postgres
  become: true
