---

- name: Allow passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo   ALL='
    line: '%sudo   ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Add user with a bash shell and group
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/bash
    groups: sudo
    append: true
  with_items: "{{ ssh_users }}"

- name: Set authorized keys for users
  authorized_key:
    user: "{{ item.0.name }}"
    state: present
    key: "{{ item.1 }}"
  loop: "{{ ssh_users | subelements('ssh_public_keys', 'skip_missing=True') }}"

- name: Remove authorized keys for users
  authorized_key:
    user: "{{ item.0.name }}"
    state: absent
    key: "{{ item.1 }}"
  loop: "{{ ssh_users | subelements('revoked_ssh_public_keys', 'skip_missing=True') }}"
