---

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Import create_swap_file.yml
  ansible.builtin.import_tasks: create_swap_file.yml
  when:
    - base_create_swap_file is defined
    - base_create_swap_file is truthy
  tags: swap

- name: Import setup_timezone.yml
  ansible.builtin.import_tasks: setup_timezone.yml
  tags: timezone

- name: Import apt.yml
  ansible.builtin.import_tasks: apt.yml
  tags: apt

- name: Import add_users.yml
  ansible.builtin.import_tasks: add_users.yml
  tags: add_users

- name: Import sshd.yml
  ansible.builtin.import_tasks: sshd.yml
  tags: sshd

- name: Import setup_needrestart.yml
  ansible.builtin.import_tasks: setup_needrestart.yml
  tags: needrestart

- name: Import setup_unattended_upgrades.yml
  ansible.builtin.import_tasks: setup_unattended_upgrades.yml
  when:
    - base_enable_unattended_upgrades is defined
    - base_enable_unattended_upgrades is truthy
  tags: unattended-upgrades

- name: Import setup_uncomplicated_firewall.yml
  ansible.builtin.import_tasks: setup_uncomplicated_firewall.yml
  when:
    - base_enable_ufw is defined
    - base_enable_ufw is truthy
  tags:
    - ufw

- name: Import setup_fail2ban.yml
  ansible.builtin.import_tasks: setup_fail2ban.yml
  when:
    - base_enable_fail2ban is defined
    - base_enable_fail2ban is truthy
  tags:
    - fail2ban

- name: Import sysctl_settings.yml
  ansible.builtin.import_tasks: sysctl_settings.yml
  when:
    - base_sysctl_settings is defined
    - base_sysctl_settings | length > 0
  tags:
    - sysctl

- name: Import setup_dropbear_initramfs.yml
  ansible.builtin.import_tasks: setup_dropbear_initramfs.yml
  when: inventory_hostname in groups["hypervisor"]
  tags:
    - initramfs
    - dropbear
