---

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Import create_swap_file.yml
  ansible.builtin.import_tasks: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Import apt.yml
  ansible.builtin.import_tasks: apt.yml
  tags: apt

- name: Import add_users.yml
  ansible.builtin.import_tasks: add_users.yml
  tags: add_users

- name: Import sshd.yml
  ansible.builtin.import_tasks: sshd.yml
  tags: sshd

- name: Import setup_needrestart.yml
  ansible.builtin.import_tasks: setup_needrestart.yml
  tags: needrestart

- name: Import setup_unattended_upgrades.yml
  ansible.builtin.import_tasks: setup_unattended_upgrades.yml
  when: enable_unattended_upgrades is defined and enable_unattended_upgrades
  tags: unattended-upgrades

- name: Import setup_uncomplicated_firewall.yml
  ansible.builtin.import_tasks: setup_uncomplicated_firewall.yml
  when: enable_ufw is defined and enable_ufw

- name: Import setup_fail2ban.yml
  ansible.builtin.import_tasks: setup_fail2ban.yml
  when: enable_fail2ban is defined and enable_fail2ban

- name: Import sysctl_settings.yml
  ansible.builtin.import_tasks: sysctl_settings.yml
  when: sysctl_settings is defined
  tags:
    - sysctl
