---

- name: Install Uncomplicated Firewall
  apt:
    update_cache: "{{ update_apt_cache }}"
    pkg: ufw
    state: present 

- name: Allow ssh connections
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: Enable ufw/firewall
  ufw:
    state: enabled
    policy: deny
