---

- name: Install fail2ban
  ansible.builtin.apt:
    update_cache: "{{ update_apt_cache }}"
    state: present
    pkg: fail2ban

- name: Set up fail2ban
  ansible.builtin.command:
    cmd: cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
    creates: /etc/fail2ban/jail.local
  notify: restart fail2ban
