---

- name: Install needrestart
  ansible.builtin.apt:
    name: needrestart
    update_cache: true

- name: Configure needrestart
  ansible.builtin.template:
    src: needrestart.conf.j2
    dest: /etc/needrestart/conf.d/fds.conf
    owner: root
    group: root
    mode: "0644"
