---

- name: Install Unattended Upgrades
  ansible.builtin.apt:
    update_cache: "{{ base_apt_update_cache }}"
    state: present
    pkg: unattended-upgrades
  retries: 3
  delay: 10

- name: Install apt-listchanges Upgrades
  ansible.builtin.apt:
    update_cache: "{{ base_apt_update_cache }}"
    state: present
    pkg: apt-listchanges
  retries: 3
  delay: 10

- name: Set up unattended upgrades
  ansible.builtin.copy:
    src: ./files/apt_periodic
    dest: /etc/apt/apt.conf.d/10periodic
    mode: "0644"

- name: Configure apt (unnattended-upgrades)
  ansible.builtin.template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"

- name: Adjust execution time
  ansible.builtin.template:
    src: unattended.timer.j2
    dest: /etc/systemd/system/apt-daily-upgrade.timer
    mode: "0644"
  notify: reload systemd
