- name: Apply sysctl settings
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value.value }}"
    sysctl_set: true
    state: present
    reload: true
  with_dict: "{{ sysctl_settings }}"
