---

- name: Base
  hosts: all
  become: true
  become_user: root
  vars_files:
    - ../local_vars/local_config.yml

  roles:
    - role: base
      tags: base
    - role: monitor
      tags: monitor
