---

- name: Deploy a farmsubsidy server
  hosts: farmsubsidyapi_backend
  become: true
  become_user: root
  vars:
    - update_apt_cache: true
  roles:
    - docker
    - nginx
    - certbot
    - farmsubsidy
