---

- name: Basic setup, networking, monitoring
  hosts: all
  roles:
    - role: base
      tags: base
    - role: network
      tags: network
      when: "not 'tst.okfn.de' in inventory_hostname or inventory_hostname == 'fds-tst.okfn.de'"

- name: Setup wireguard
  hosts: vpn
  roles:
    - role: wireguard
      tags: wireguard

- name: Create db server
  hosts: db
  roles:
    - role: db
      tags: db

- name: Create mail server
  hosts: mail
  roles:
    - role: certbot
      tags: certbot
    - role: postfix
      tags: postfix
      when: "not 'tst.okfn.de' in inventory_hostname"
    - role: test/postfix
      tags: postfix
      when: "'tst.okfn.de' in inventory_hostname"
    - role: dovecot
      tags: dovecot
  tags: mail

- name: Create search server
  hosts: search
  roles:
    - elasticsearch
  tags:
    - elasticsearch

- name: Create queue server
  hosts: queue
  roles:
    - rabbitmq
  tags:
    - rabbitmq

- name: Create broker server
  hosts: broker

  roles:
    - redis
  tags:
    - redis

- name: Create cache server
  hosts: cache
  roles:
    - memcached
  tags:
    - memcached

- name: Create media server
  hosts: media
  roles:
    - role: nginx
      tags: nginx
    - role: certbot
      tags: certbot
  tags: mediaserver

- name: Create monitor server
  hosts: monitor
  roles:
    - role: nginx
      tags: nginx
      when: "inventory_hostname != 'fds-tst.okfn.de'"
    - role: certbot
      tags: certbot
  tags: monitorserver

- name: Create app server
  hosts: app
  roles:
    - app
    - appserver
  tags:
    - app
    - appserver

- name: Create web server
  hosts: web
  roles:
    - role: nginx
      tags: nginx
    - role: certbot
      tags: certbot
  tags: webserver

- name: Create worker server
  hosts: app
  roles:
    - role: app
      tags: app
    - role: celery
      tags: celery
  tags:
    - app
    - celery
