---

- name: Basic setup, networking, monitoring
  hosts: all
  become: true
  become_user: root
  vars_files:
    - ../local_vars/local_config.yml
  roles:
    - role: base
      tags: base
    - role: network
      tags: network
      when: "not 'tst.okfn.de' in inventory_hostname"
    - role: check_mk
      tags: check_mk
      when: "not 'tst.okfn.de' in inventory_hostname"

- name: Create db server
  hosts: db
  become: true
  become_user: root
  vars_files:
    - ../local_vars/local_config.yml
  roles:
    - role: db
      tags: db

- name: Create mail server
  hosts: mail
  become: true
  become_user: root
  vars_files:
    - ../local_vars/local_config.yml
  roles:
    - role: postfix
      tags: postfix
      when: "not 'tst.okfn.de' in inventory_hostname"
    - role: test/postfix
      tags: postfix
      when: "'tst.okfn.de' in inventory_hostname"
    - role: dovecot
      tags: dovecot
  tags: mail

- name: Create search server
  hosts: search
  become: true
  become_user: root
  vars_files:
    - ../local_vars/local_config.yml
  roles:
    - elasticsearch
  tags:
    - elasticsearch

- name: Create queue server
  hosts: queue
  become: true
  become_user: root
  vars_files:
    - ../local_vars/local_config.yml
  roles:
    - rabbitmq
  tags:
    - rabbitmq

- name: Create broker server
  hosts: broker
  become: true
  become_user: root
  vars_files:
    - ../local_vars/local_config.yml
  roles:
    - redis
  tags:
    - redis

- name: Create cache server
  hosts: cache
  become: true
  become_user: root
  vars_files:
    - ../local_vars/local_config.yml
  roles:
    - memcached
  tags:
    - memcached

- name: Create media server
  hosts: media
  become: true
  become_user: root
  vars_files:
    - ../local_vars/local_config.yml
  roles:
    - role: nginx
      tags: nginx
    - role: certbot
      tags: certbot
  tags: mediaserver

- name: Create app server
  hosts: app
  become: true
  become_user: root
  vars_files:
    - ../local_vars/local_config.yml
  roles:
    - app
    - appserver
  tags:
    - app
    - appserver

- name: Create web server
  hosts: web
  become: true
  become_user: root
  vars_files:
    - ../local_vars/local_config.yml
  roles:
    - role: nginx
      tags: nginx
    - role: certbot
      tags: certbot
  tags: webserver

- name: Create worker server
  hosts: app
  become: true
  become_user: root
  vars_files:
    - ../local_vars/local_config.yml
  roles:
    - role: app
      tags: app
    - role: celery
      tags: celery
  tags:
    - app
    - celery
