---

- name: Deploy an ogimage instance
  hosts: auxiliary
  become: true
  become_user: root
  roles:
    - role: docker
      tags: docker
    - role: nginx
      tags: docker
    - role: certbot
      tags: certbot
    - role: ogimage
      tags: ogimage
