---

- name: Deploy an ogimage instance
  hosts: auxiliary
  become: true
  become_user: root
  roles:
    - role: docker
      tags: docker
    - role: nginx
      tags: docker
    - role: certbot
      tags: certbot
      when: "not 'tst.okfn.de' in inventory_hostname"
    - role: test/fake-certbot
      tags: certbot
      when: "'tst.okfn.de' in inventory_hostname"
    - role: ogimage
      tags: ogimage
