---

- name: Deploy a sentry instance
  hosts: auxiliary
  become: true
  become_user: root
  roles:
    - role: docker
      tags: docker
    - role: certbot
      tags: certbot
    - role: nginx
      tags: nginx
    - role: sentry
      tags: sentry
