---

- name: services
  hosts: all
  become: true
  become_user: root
  vars_files:
    - ../local_vars/local_config.yml

  roles:
    - role: fdsbot
      tags: fdsbot
      when: inventory_hostname in groups["fdsbot"]
    - role: icinga
      tags: icinga
      when: inventory_hostname in groups["monitor"]
