---

- name: services
  hosts: all
  become: true
  become_user: root

  roles:
    - role: fdsbot
      tags: fdsbot
      when: inventory_hostname in groups["fdsbot"]
    - role: icinga
      tags: icinga
      when: inventory_hostname in groups["monitor"]
