---

- name: Deploy a weblate instance
  hosts: auxiliary
  become: true
  become_user: root
  roles:
    - role: docker
      tags: docker
    - role: nginx
      tags: nginx
    - role: certbot
      tags: certbot
    - role: weblate
      tags: weblate
