---

- name: Install Memcached
  ansible.builtin.apt:
    name: memcached
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags: packages
  retries: 30
  delay: 10

- name: Create the Memcached configuration file
  ansible.builtin.template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
    mode: "0644"
    backup: true
  notify:
    - restart memcached

- name: Ensure the Memcached service is running
  ansible.builtin.service:
    name: memcached
    state: started
    enabled: true
