name: FragDenStaat Ansible CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create vault.key dummy
        run: |
          echo "false" > vault.key
      - name: run-ansible-lint
        uses: ansible/ansible-lint@v25.4.0
