name: FragDenStaat Ansible CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create vault.key dummy
        run: |
          echo "false" > vault.key
      - name: run-ansible-lint
        uses: ansible/ansible-lint@v25.4.0
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
      - name: yamllint
        run: |
          apt update
          apt install yamllint -y
          find . -name "*.yml" -exec yamllint {} \;
